/** Relações didáticas de Biologia. Os valores relativos servem para explorar
 * o mecanismo, sem fingir medidas clínicas ou ambientais reais. */
export const BIOLOGY_REMAINING = {
  'genetics-intro': ['Segregação de alelos', 'Quais gametas um heterozigoto Aa produz?', 'Genótipo parental', 0, 2, 1, 1, '', 'AA → só A; Aa → metade A e metade a; aa → só a', 'Cada gameta recebe um dos alelos do par na meiose.', ['Par Aa', 'Separação', 'Gametas']],
  'blood-groups': ['Compatibilidade ABO', 'Quem pode receber hemácias do tipo A em uma transfusão ABO?', 'Tipo ABO do receptor', 0, 3, 1, 0, '', 'antígeno A da hemácia + anti-A do receptor → aglutinação', 'Receptores O e B têm anti-A e não recebem hemácias A; receptores A e AB não têm anti-A. Considere aqui apenas o sistema ABO.', ['Hemácia A', 'Anti-A no plasma?', 'Compatibilidade']],
  locomotion: ['Alavanca muscular', 'O que a contração faz a uma articulação?', 'Intensidade relativa', 0, 100, 10, 40, '%', 'músculo contrai → traciona tendão → osso gira', 'Músculos esqueléticos puxam ossos via tendões; antagonistas produzem movimentos opostos.', ['Músculo', 'Tendão', 'Osso']],
  endocrine: ['Realimentação hormonal', 'O que ocorre quando aumenta o hormônio periférico?', 'Hormônio periférico', 0, 100, 10, 40, '%', 'hipófise → glândula → hormônio ⊣ hipófise', 'Na realimentação negativa, o produto reduz o estímulo que iniciou sua produção.', ['Hipófise', 'Glândula', 'Retorno']],
  'air-pollution': ['Dispersão de poluentes', 'Como a emissão altera a concentração no ar?', 'Emissão relativa', 0, 100, 10, 40, '%', 'emissão → dispersão/transformação → exposição', 'A concentração depende da emissão e das condições de dispersão; o desenho não representa uma cidade real.', ['Fonte', 'Atmosfera', 'Exposição']],
  'climate-pops': ['Persistência e biorremediação', 'O que muda quando microrganismos degradam um contaminante?', 'Degradação relativa', 0, 100, 10, 30, '%', 'contaminante → transformação biológica → menor disponibilidade', 'Biorremediação depende do organismo, do composto e das condições do ambiente; não elimina todo contaminante automaticamente.', ['Composto', 'Microrganismo', 'Ambiente']],
  inorganic: ['Água, soluto e osmose', 'Para onde a água se move através de uma membrana?', 'Soluto externo', 0, 100, 10, 50, '%', 'mais soluto efetivo → menor potencial hídrico → fluxo de água', 'Na osmose, a água atravessa a membrana em resposta à diferença de potencial hídrico.', ['Solução', 'Membrana', 'Célula']],
  'cytoplasm-one': ['Citoesqueleto em ação', 'Que estrutura sustenta forma e transporte celular?', 'Organização relativa', 0, 100, 10, 50, '%', 'filamentos + microtúbulos → forma, transporte e divisão', 'Os componentes do citoesqueleto têm funções distintas; a célula não é uma bolsa sem organização interna.', ['Filamentos', 'Trilhas', 'Movimento']],
  'cytoplasm-two': ['Rota de secreção', 'Qual é o percurso de uma proteína exportada?', 'Etapa da rota', 0, 2, 1, 0, '', 'RER → complexo golgiense → vesícula/exocitose', 'Proteínas de secreção entram no retículo rugoso, são modificadas no Golgi e seguem em vesículas.', ['RER', 'Golgi', 'Exterior']],
  nucleus: ['Acesso ao DNA', 'Como a condensação altera o acesso aos genes?', 'Condensação relativa', 0, 100, 10, 40, '%', 'cromatina menos condensada → maior acesso à transcrição', 'Eucromatina tende a ser mais acessível que heterocromatina; condensação não muda a sequência de bases.', ['DNA', 'Cromatina', 'RNA']],
  'chromosome-mutations': ['Não disjunção e gametas', 'O que uma separação incompleta produz?', 'Etapa alterada', 0, 2, 1, 1, '', 'não disjunção → gametas com n + 1 ou n − 1', 'A falha de segregação altera o número de cromossomos nos gametas formados.', ['Cromossomos', 'Separação', 'Gametas']],
  biotechnology: ['Amplificação por PCR', 'Como ciclos repetidos aumentam um fragmento de DNA?', 'Ciclos de amplificação', 0, 30, 5, 10, ' ciclos', 'desnaturação → anelamento → extensão → cópias', 'PCR amplifica uma sequência definida por iniciadores; não é uma técnica de edição gênica.', ['DNA molde', 'Ciclo', 'Cópias']],
  cnidarians: ['Organização animal', 'Que mudança separa poríferos de cnidários?', 'Nível de organização', 0, 1, 1, 0, '', 'poríferos: sem tecidos verdadeiros; cnidários: tecidos e cnidócitos', 'Poríferos filtram água por coanócitos; cnidários têm tecidos e cavidade gastrovascular.', ['Porífero', 'Critério', 'Cnidário']],
  'body-plan': ['Plano corporal e cavidade', 'Como a cavidade corporal organiza o corpo do animal?', 'Tipo de cavidade', 0, 2, 1, 1, '', 'acelomado → pseudocelomado → celomado', 'Platelmintos são acelomados; nematódeos são pseudocelomados e possuem tubo digestório completo.', ['Parede', 'Cavidade', 'Órgãos']],
  insects: ['Reconhecimento de artrópodes', 'Que combinação ajuda a reconhecer o grupo?', 'Pares de pernas', 2, 5, 1, 3, ' pares', 'tagmas + antenas + pernas → identificação do grupo', 'Insetos têm três pares de pernas; crustáceos, quilópodes e diplópodes exigem outros caracteres além da contagem.', ['Tagmas', 'Apêndices', 'Grupo']],
  arachnids: ['Plano do aracnídeo', 'Qual traço separa aracnídeos de insetos?', 'Pares de pernas', 3, 5, 1, 4, ' pares', 'quatro pares de pernas + quelíceras + ausência de antenas', 'Aracnídeos não são insetos: têm quatro pares de pernas e não possuem antenas.', ['Quelíceras', 'Pernas', 'Aracnídeo']],
  fish: ['Peixes e flutuabilidade', 'Como a estrutura do peixe se relaciona à vida aquática?', 'Tipo de esqueleto', 0, 1, 1, 0, '', 'cartilaginoso ou ósseo → diferenças em brânquias e flutuabilidade', 'Peixes ósseos e cartilaginosos compartilham adaptações aquáticas, mas diferem em estruturas e estratégias.', ['Esqueleto', 'Brânquias', 'Meio']],
  angiosperms: ['Semente, flor e fruto', 'Que estrutura se forma após a fecundação em angiospermas?', 'Estrutura em foco', 0, 2, 1, 1, '', 'óvulo → semente; ovário → fruto', 'Em angiospermas, o fruto deriva do ovário e a semente deriva do óvulo.', ['Flor', 'Fecundação', 'Fruto']],
  procaryotes: ['Transferência gênica bacteriana', 'Como bactérias podem adquirir genes sem reprodução sexual?', 'Via de transferência', 0, 2, 1, 0, '', 'transformação, transdução ou conjugação → DNA adquirido', 'Transferência horizontal altera a composição genética da população, mas não equivale a reprodução sexual.', ['Doador', 'DNA', 'Receptora']],
  senses: ['Transdução sensorial', 'Como um estímulo vira sinal nervoso?', 'Intensidade do estímulo', 0, 100, 10, 40, '%', 'receptor → transdução → impulso nervoso', 'O receptor converte energia do estímulo em sinal elétrico; visão e audição usam receptores diferentes.', ['Estímulo', 'Receptor', 'Nervo']],
  reproduction: ['Onde cada método atua?', 'Em que etapa um método contraceptivo reduz a chance de gestação?', 'Etapa do processo', 0, 2, 1, 1, '', 'ovulação → fecundação → implantação', 'Métodos diferem em mecanismo e eficácia; o modelo localiza etapas, sem substituir orientação em saúde.', ['Ovulação', 'Fecundação', 'Implantação']],
  'plant-tissues': ['Tecidos vegetais', 'Que tecido participa do transporte de seiva?', 'Tecido em foco', 0, 2, 1, 0, '', 'xilema conduz água e sais; floema distribui açúcares', 'A posição e a função dos tecidos ajudam a identificar raiz, caule e folha.', ['Tecido', 'Condução', 'Órgão']],
  'stems-leaves': ['Caule e folha', 'Como a estrutura favorece a função do órgão?', 'Órgão em foco', 0, 2, 1, 1, '', 'caule sustenta/conduz; folha realiza trocas e fotossíntese', 'Morfologia vegetal deve ser relacionada à função: órgãos possuem tecidos e adaptações diferentes.', ['Estrutura', 'Troca', 'Função']],
} as const;
export type BiologyRemainingId = keyof typeof BIOLOGY_REMAINING;
export function biologyRemainingReadout(id: BiologyRemainingId, value: number): string {
  const pick = (items: string[]) => items[Math.max(0, Math.min(items.length - 1, Math.round(value)))] ?? '';
  if (id === 'genetics-intro') return pick(['AA: 100% A', 'Aa: 50% A e 50% a', 'aa: 100% a']);
  if (id === 'blood-groups') return pick(['O: incompatível (anti-A)', 'A: compatível', 'B: incompatível (anti-A)', 'AB: compatível']);
  if (id === 'endocrine') return `${100 - value}% de estímulo relativo`;
  if (id === 'cytoplasm-two') return pick(['RER: síntese e entrada', 'Golgi: modificação e triagem', 'Vesícula: exocitose']);
  if (id === 'chromosome-mutations') return pick(['mitose: linhagem somática', 'meiose I: pares homólogos', 'meiose II: cromátides-irmãs']);
  if (id === 'cnidarians') return pick(['porífero: sem tecidos verdadeiros', 'cnidário: tecidos verdadeiros']);
  if (id === 'body-plan') return pick(['acelomado', 'pseudocelomado', 'celomado']);
  if (id === 'fish') return pick(['cartilaginoso', 'ósseo']);
  if (id === 'angiosperms') return pick(['flor', 'semente (do óvulo)', 'fruto (do ovário)']);
  if (id === 'procaryotes') return pick(['transformação', 'transdução', 'conjugação']);
  if (id === 'reproduction') return pick(['ovulação', 'fecundação', 'implantação']);
  if (id === 'plant-tissues') return pick(['xilema: água e sais', 'floema: açúcares', 'epiderme: revestimento']);
  if (id === 'stems-leaves') return pick(['raiz', 'caule', 'folha']);
  if (id === 'biotechnology') return `${2 ** Math.round(value)} cópias relativas`;
  return `${value}% relativo`;
}
