/** Instrumentos de Química: parâmetros em unidades explícitas e relações
 *  verificáveis. Cada configuração corresponde a um capítulo exato. */
export type ChemistryId =
  | 'gas-state' | 'gas-law' | 'separation' | 'balancing' | 'mole' | 'formula'
  | 'stoichiometry' | 'carbon-chain' | 'organic-name' | 'addition'
  | 'oxidation' | 'esterification' | 'biodiesel' | 'acidity' | 'polymer'
  | 'equilibrium-shift' | 'ionic-equilibrium' | 'acid-weathering';

export interface ChemistryConfig {
  title: string;
  question: string;
  control: string;
  min: number;
  max: number;
  step: number;
  initial: number;
  unit: string;
  relation: string;
  explanation: string;
  read: (value: number) => { label: string; value: string; secondary: string };
  /** Diagram family: each represents a different physical or symbolic object. */
  diagram: 'particles' | 'apparatus' | 'equation' | 'molecule' | 'energy' | 'equilibrium';
}

const n = (v: number, digits = 2) => Number(v.toFixed(digits)).toLocaleString('pt-BR');
export const gasPressure = (moles: number, temperatureKelvin: number, volumeLiters: number) => moles * 0.082057 * temperatureKelvin / volumeLiters;
export const molarAmount = (massGrams: number, molarMass: number) => massGrams / molarMass;
export const limitingProduct = (hydrogenMoles: number, oxygenMoles: number) => Math.min(hydrogenMoles / 2, oxygenMoles) * 2;
export const weakAcidPH = (concentration: number, ka: number) => -Math.log10((-ka + Math.sqrt(ka * ka + 4 * ka * concentration)) / 2);
export const equilibriumQuotient = (products: number, reactants: number) => products / reactants;

export const CHEMISTRY: Record<ChemistryId, ChemistryConfig> = {
  'gas-state': { title: 'Partículas em um recipiente', question: 'O que muda na pressão quando a temperatura sobe e o volume permanece?', control: 'Temperatura', min: 200, max: 500, step: 10, initial: 300, unit: 'K', relation: 'P = nRT / V · n = 1 mol · V = 10 L', explanation: 'Mais energia cinética aumenta a frequência e a intensidade dos choques contra a parede.', diagram: 'particles', read: v => ({ label: 'Pressão ideal', value: `${n(gasPressure(1, v, 10))} atm`, secondary: `T = ${v} K; V = 10 L` }) },
  'gas-law': { title: 'Seringa de gás ideal', question: 'A mesma amostra ocupa quanto volume ao aquecer sob pressão constante?', control: 'Temperatura final', min: 200, max: 600, step: 10, initial: 300, unit: 'K', relation: 'V₂ = V₁ · T₂ / T₁ · V₁ = 2 L; T₁ = 300 K', explanation: 'Use temperatura absoluta. Aumentar kelvin em pressão constante expande o gás.', diagram: 'particles', read: v => ({ label: 'Volume final', value: `${n(2 * v / 300)} L`, secondary: 'Pressão e quantidade de matéria constantes' }) },
  separation: { title: 'Filtração por tamanho', question: 'Quais partículas atravessam a malha do filtro?', control: 'Abertura dos poros', min: 1, max: 10, step: 1, initial: 4, unit: 'µm', relation: 'Passam partículas menores que o poro; sólidos maiores ficam retidos.', explanation: 'Filtração separa uma fase sólida dispersa no líquido; substâncias dissolvidas atravessam o filtro.', diagram: 'apparatus', read: v => ({ label: 'Areia (8 µm)', value: v > 8 ? 'atravessa' : 'retida', secondary: `Partículas finas (2 µm): ${v > 2 ? 'atravessam' : 'retidas'}` }) },
  balancing: { title: 'Conservação de átomos', question: 'Quantas moléculas de água surgem ao reagir hidrogênio e oxigênio?', control: 'Lotes de reação', min: 1, max: 6, step: 1, initial: 2, unit: 'lotes', relation: '2 H₂ + O₂ → 2 H₂O', explanation: 'Cada lote consome 2 H₂ e 1 O₂. Coeficientes mudam a quantidade de moléculas, nunca os índices dos átomos na fórmula.', diagram: 'equation', read: v => ({ label: 'Água formada', value: `${2 * v} H₂O`, secondary: `${2 * v} H₂ + ${v} O₂; H: ${4 * v} = ${4 * v}; O: ${2 * v} = ${2 * v}` }) },
  mole: { title: 'Da massa ao mol', question: 'Quantas entidades há em uma amostra de água?', control: 'Massa de H₂O', min: 18, max: 180, step: 18, initial: 36, unit: 'g', relation: 'n = m / M · M(H₂O) = 18 g/mol', explanation: 'Um mol contém 6,022 × 10²³ entidades; massa molar é a ponte entre gramas e mols.', diagram: 'particles', read: v => ({ label: 'Quantidade de matéria', value: `${n(molarAmount(v, 18))} mol`, secondary: `${n(v / 18 * 6.022)} × 10²³ moléculas` }) },
  formula: { title: 'Fórmula mínima e molecular', question: 'Quantas unidades da fórmula mínima cabem na molécula?', control: 'Massa molar experimental', min: 30, max: 180, step: 30, initial: 60, unit: 'g/mol', relation: 'Fórmula mínima CH₂O · M = 30 g/mol; fator = M molecular / 30', explanation: 'A composição percentual determina a proporção mínima; a massa molar determina o múltiplo molecular.', diagram: 'molecule', read: v => ({ label: 'Fórmula molecular', value: `C${v / 30}H${2 * v / 30}O${v / 30}`, secondary: `${v / 30} unidade(s) CH₂O` }) },
  stoichiometry: { title: 'Reagente limitante', question: 'Quanto produto se forma com oxigênio disponível fixo?', control: 'Hidrogênio disponível', min: 0, max: 8, step: 1, initial: 2, unit: 'mol H₂', relation: '2 H₂ + O₂ → 2 H₂O · O₂ disponível = 2 mol', explanation: 'A proporção é 2:1. Depois de 4 mol de H₂, o oxigênio limita o produto.', diagram: 'equation', read: v => ({ label: 'Água produzida', value: `${n(limitingProduct(v, 2))} mol`, secondary: v > 4 ? `sobram ${v - 4} mol H₂` : `${n(2 - v / 2)} mol O₂ restante` }) },
  'carbon-chain': { title: 'Topologia da cadeia', question: 'Como a ramificação muda o esqueleto de carbono?', control: 'Carbonos no ramo', min: 0, max: 3, step: 1, initial: 1, unit: 'C', relation: 'Cadeia principal com 4 carbonos; ramo ligado ao carbono 2.', explanation: 'A classificação considera fechamento, ramificação, saturação e heteroátomos como critérios distintos.', diagram: 'molecule', read: v => ({ label: 'Classificação', value: v ? 'aberta e ramificada' : 'aberta e normal', secondary: `${4 + v} carbonos; ligações simples` }) },
  'organic-name': { title: 'Nome pela cadeia principal', question: 'Qual prefixo expressa a quantidade de carbonos?', control: 'Carbonos na cadeia', min: 1, max: 8, step: 1, initial: 4, unit: 'C', relation: 'prefixo + an (ligações simples) + o (hidrocarboneto)', explanation: 'Conte a cadeia principal antes de escolher o prefixo. Ramificações e insaturações exigem localização.', diagram: 'molecule', read: v => ({ label: 'Alcano linear', value: `${['', 'metano', 'etano', 'propano', 'butano', 'pentano', 'hexano', 'heptano', 'octano'][v]}`, secondary: `C${v}H${2 * v + 2}` }) },
  addition: { title: 'Adição ao alceno', question: 'Quantas ligações duplas são consumidas na hidrogenação?', control: 'H₂ disponível', min: 0, max: 4, step: 1, initial: 1, unit: 'mol', relation: 'C₂H₄ + H₂ → C₂H₆ (catalisador)', explanation: 'A ligação π é rompida e novos átomos se ligam aos carbonos; uma dupla consome um H₂.', diagram: 'molecule', read: v => ({ label: 'Etano formado', value: `${Math.min(v, 2)} mol`, secondary: `Eteno inicial: 2 mol; ${2 - Math.min(v, 2)} mol sem reagir` }) },
  oxidation: { title: 'Combustão e oxigênio', question: 'A disponibilidade de O₂ permite a combustão completa do metano?', control: 'Oxigênio disponível', min: 0, max: 4, step: 0.5, initial: 2, unit: 'mol', relation: 'CH₄ + 2 O₂ → CO₂ + 2 H₂O', explanation: 'Dois mols de O₂ por mol de CH₄ garantem a estequiometria da combustão completa. Com menos, há oxigênio insuficiente.', diagram: 'equation', read: v => ({ label: 'Combustão completa', value: v >= 2 ? 'O₂ suficiente' : 'O₂ insuficiente', secondary: `${n(Math.max(0, 2 - v))} mol O₂ faltante para 1 mol CH₄` }) },
  esterification: { title: 'Éster e água', question: 'Quanto éster pode se formar antes do equilíbrio?', control: 'Álcool disponível', min: 0, max: 5, step: 1, initial: 2, unit: 'mol', relation: 'Ácido + álcool ⇌ éster + água (proporção 1:1)', explanation: 'Este é o teto estequiométrico; a reação reversível não garante conversão total sem deslocar o equilíbrio.', diagram: 'equilibrium', read: v => ({ label: 'Teto de éster', value: `${Math.min(v, 3)} mol`, secondary: 'Ácido disponível: 3 mol; rendimento real pode ser menor' }) },
  biodiesel: { title: 'Transesterificação', question: 'Qual é o teto estequiométrico do biodiesel?', control: 'Álcool disponível', min: 0, max: 12, step: 1, initial: 6, unit: 'mol', relation: 'Triglicerídeo + 3 álcool ⇌ 3 ésteres + glicerol', explanation: 'Cada triglicerídeo tem três cadeias graxas; três moléculas de álcool geram até três ésteres.', diagram: 'equilibrium', read: v => ({ label: 'Ésteres máximos', value: `${Math.min(v, 6)} mol`, secondary: 'Triglicerídeo: 2 mol; conversão real depende do equilíbrio' }) },
  acidity: { title: 'Escala de pKa', question: 'O que o pKa revela sobre a dissociação?', control: 'pKa', min: 1, max: 7, step: 1, initial: 4, unit: '', relation: 'Ka = 10⁻ᵖᴷᵃ; ácido de menor pKa é mais forte (mesmo solvente).', explanation: 'Compare o equilíbrio de dissociação em condições iguais; pKa não é o pH da solução.', diagram: 'equilibrium', read: v => ({ label: 'Constante Ka', value: `10⁻${v}`, secondary: `pH aproximado a 0,1 mol/L: ${n(weakAcidPH(0.1, 10 ** -v))}` }) },
  polymer: { title: 'Grau de polimerização', question: 'Quantas unidades repetidas compõem a cadeia?', control: 'Unidades do monômero', min: 2, max: 12, step: 1, initial: 5, unit: '', relation: 'n CH₂=CH₂ → [–CH₂–CH₂–]ₙ', explanation: 'Na polimerização por adição, as duplas se abrem e os monômeros se unem sem liberar molécula pequena.', diagram: 'molecule', read: v => ({ label: 'Cadeia de polietileno', value: `${v} unidades`, secondary: `${2 * v} carbonos no segmento representado` }) },
  'equilibrium-shift': { title: 'Quociente da reação', question: 'Em que direção a composição precisa evoluir para atingir o equilíbrio?', control: 'Produtos / reagentes', min: 0.2, max: 4, step: 0.2, initial: 1, unit: '', relation: 'Q = [produtos]/[reagentes]; neste modelo K = 1.', explanation: 'Se Q < K, a reação avança para produtos; se Q > K, favorece reagentes. K depende da temperatura.', diagram: 'equilibrium', read: v => ({ label: 'Sentido espontâneo', value: Math.abs(v - 1) < 0.001 ? 'em equilíbrio' : v < 1 ? 'para os produtos →' : '← para os reagentes', secondary: `Q = ${n(equilibriumQuotient(v, 1))}; K = 1` }) },
  'ionic-equilibrium': { title: 'Diluição de ácido fraco', question: 'Como o pH responde à diluição do ácido acético?', control: 'Concentração inicial', min: 0.01, max: 0.2, step: 0.01, initial: 0.1, unit: 'mol/L', relation: 'HA ⇌ H⁺ + A⁻ · Ka = 1,8 × 10⁻⁵', explanation: 'Diluir reduz [H⁺], elevando o pH, embora a fração ionizada do ácido fraco aumente.', diagram: 'equilibrium', read: v => ({ label: 'pH de equilíbrio', value: n(weakAcidPH(v, 1.8e-5)), secondary: `Concentração inicial: ${n(v)} mol/L` }) },
  'acid-weathering': { title: 'Carbonato e acidez', question: 'Como a acidez influencia a dissolução de carbonato?', control: 'pH da solução', min: 3, max: 8, step: 0.5, initial: 6, unit: '', relation: 'CaCO₃(s) + 2 H⁺(aq) → Ca²⁺(aq) + CO₂(g) + H₂O(l)', explanation: 'Mais H⁺ favorece a dissolução do carbonato. Este esquema compara disponibilidade de prótons, não taxa de reação.', diagram: 'apparatus', read: v => ({ label: 'Disponibilidade de H⁺', value: `${n(10 ** (7 - v))} × a pH 7`, secondary: `pH ${n(v)} · [H⁺] = 10⁻${n(v)} mol/L` }) },
};
