export type ElectricId = 'current' | 'power' | 'resistor' | 'kirchhoff' | 'capacitor';
export interface ElectricReadout { label: string; value: string; pivot?: boolean }
export interface ElectricConfig { id: ElectricId; name: string; question: string; control: { label: string; description: string; min: number; max: number; step: number; initial: number }; formula: string; insight: string; readouts(value: number): ElectricReadout[] }
const decimal = (n: number) => String(Math.round(n * 10) / 10).replace('.', ',');

export const ELECTRIC: Record<ElectricId, ElectricConfig> = {
  current: { id: 'current', name: 'Corrente conta carga que atravessa uma seção', question: 'Mude a carga que atravessa o fio em 2 s.', control: { label: 'ΔQ', description: 'carga que atravessa em C', min: 0, max: 16, step: 1, initial: 8 }, formula: 'i = ΔQ/Δt', insight: 'corrente não é carga acumulada: mede quanta carga atravessa uma seção a cada intervalo de tempo.', readouts: q => [{ label: 'Tempo', value: '2 s' }, { label: 'Corrente i', value: `${decimal(q / 2)} A`, pivot: true }] },
  power: { id: 'power', name: 'Potência é a taxa de transformação elétrica', question: 'Mude a corrente sob tensão constante de 12 V.', control: { label: 'i', description: 'corrente em A', min: 0, max: 8, step: 1, initial: 3 }, formula: 'P = Ui', insight: 'para a mesma tensão, dobrar a corrente dobra a potência transferida a cada segundo.', readouts: i => [{ label: 'Tensão U', value: '12 V' }, { label: 'Potência P', value: `${12 * i} W`, pivot: true }] },
  resistor: { id: 'resistor', name: 'Resistência controla a corrente no circuito ôhmico', question: 'Mude a resistência ligada a uma fonte ideal de 12 V.', control: { label: 'R', description: 'resistência em Ω', min: 1, max: 12, step: 1, initial: 4 }, formula: 'U = Ri', insight: 'mantida a tensão, resistência maior reduz a corrente; a relação é inversa, não linear.', readouts: r => [{ label: 'Tensão U', value: '12 V' }, { label: 'Corrente i', value: `${decimal(12 / r)} A`, pivot: true }] },
  kirchhoff: { id: 'kirchhoff', name: 'No nó, a corrente se distribui e se conserva', question: 'Mude a corrente que entra em um nó com um ramo fixo de 2 A.', control: { label: 'I entrada', description: 'corrente antes da bifurcação em A', min: 2, max: 12, step: 1, initial: 7 }, formula: 'ΣI entra = ΣI sai', insight: 'carga não se acumula no nó: a corrente de entrada precisa ser igual à soma das correntes de saída.', readouts: input => [{ label: 'Ramo A', value: '2 A' }, { label: 'Ramo B', value: `${input - 2} A` }, { label: 'Verificação', value: `${input} A = 2 A + ${input - 2} A`, pivot: true }] },
  capacitor: { id: 'capacitor', name: 'Capacitor separa cargas e armazena energia', question: 'Mude a tensão entre placas de um capacitor de 2 μF.', control: { label: 'U', description: 'diferença de potencial em V', min: 0, max: 12, step: 1, initial: 6 }, formula: 'Q = CU; E = CU²/2', insight: 'cargas opostas se acumulam nas placas; elevar a tensão aumenta carga linearmente e energia quadraticamente.', readouts: u => [{ label: 'Carga |Q|', value: `${2 * u} μC` }, { label: 'Energia', value: `${u * u} μJ`, pivot: true }] },
};
