export type ElectrostaticsId = 'coulomb' | 'field' | 'potential' | 'uniform-field' | 'charge-dynamics';
export interface ElectroReadout { label: string; value: string; pivot?: boolean }
export interface ElectroConfig { id: ElectrostaticsId; name: string; question: string; control: { label: string; description: string; min: number; max: number; step: number; initial: number }; formula: string; insight: string; readouts(value: number): ElectroReadout[] }
const show = (n: number) => String(Math.round(n * 10) / 10).replace('.', ',');
export const ELECTRO: Record<ElectrostaticsId, ElectroConfig> = {
  coulomb: { id: 'coulomb', name: 'Distância enfraquece a força elétrica ao quadrado', question: 'Mude a separação entre duas cargas de sinais opostos.', control: { label: 'r', description: 'distância em unidades relativas', min: 1, max: 8, step: 1, initial: 3 }, formula: 'F = k|qQ|/r²', insight: 'dobrar a distância não divide a força por dois: divide por quatro; o sinal só determina atração ou repulsão.', readouts: r => [{ label: 'Cargas', value: '+q e −Q' }, { label: 'Força relativa', value: `${show(36 / (r * r))} F₀`, pivot: true }] },
  field: { id: 'field', name: 'Campo é força disponível por unidade de carga', question: 'Mude a distância até uma carga positiva fixa.', control: { label: 'r', description: 'distância em unidades relativas', min: 1, max: 8, step: 1, initial: 3 }, formula: 'E = k|Q|/r²', insight: 'o campo existe mesmo sem carga de prova; linhas saem da carga positiva e sua densidade indica intensidade.', readouts: r => [{ label: 'Sentido', value: 'para fora de +Q' }, { label: 'Campo relativo', value: `${show(36 / (r * r))} E₀`, pivot: true }] },
  potential: { id: 'potential', name: 'Potencial é energia por unidade de carga', question: 'Mude a distância até uma carga positiva fixa.', control: { label: 'r', description: 'distância em unidades relativas', min: 1, max: 10, step: 1, initial: 4 }, formula: 'V = kQ/r', insight: 'potencial é escalar: para carga positiva diminui com a distância sem precisar indicar uma direção.', readouts: r => [{ label: 'Sinal de V', value: 'positivo' }, { label: 'Potencial relativo', value: `${show(24 / r)} V₀`, pivot: true }] },
  'uniform-field': { id: 'uniform-field', name: 'Placas transformam distância em diferença de potencial', question: 'Mude a separação percorrida em um campo de 4 V/m.', control: { label: 'd', description: 'deslocamento na direção do campo em m', min: 0, max: 8, step: 1, initial: 3 }, formula: '|ΔV| = Ed', insight: 'em campo uniforme, o potencial cai linearmente no sentido do campo; equipotenciais são perpendiculares às linhas.', readouts: d => [{ label: 'Campo E', value: '4 V/m' }, { label: '|ΔV|', value: `${4 * d} V`, pivot: true }] },
  'charge-dynamics': { id: 'charge-dynamics', name: 'Campo acelera cargas conforme q/m', question: 'Mude a intensidade de um campo que atua em uma carga positiva.', control: { label: 'E', description: 'campo elétrico em N/C', min: 0, max: 10, step: 1, initial: 4 }, formula: 'F = qE; a = qE/m', insight: 'o sentido da força acompanha o campo para q positiva e inverte para q negativa; massa maior reduz aceleração.', readouts: e => [{ label: 'Carga', value: '+2 C' }, { label: 'Força', value: `${2 * e} N`, pivot: true }] },
};
