export type MatrixConfigId = 'sistemas' | 'matrizes' | 'produto' | 'determinante' | 'discussao';
export interface MatrixReadout { label: string; value: string; pivot?: boolean }
export interface MatrixConfig { id: MatrixConfigId; name: string; question: string; control: { label: string; description: string; min: number; max: number; step: number; initial: number }; formula: string; insight: string; readouts(value: number): MatrixReadout[] }
const n = (x:number) => String(Math.round(x * 100) / 100).replace('.', ',').replace('-', '−');
export const MATRIX_CONFIGS: Record<MatrixConfigId, MatrixConfig> = {
  sistemas: { id:'sistemas', name:'Duas condições se encontram no mesmo ponto', question:'Escolha x e veja se o par satisfaz simultaneamente x + y = 10 e x − y = 2.', control:{label:'x',description:'coordenada testada no sistema',min:0,max:10,step:1,initial:6}, formula:'x + y = 10; x − y = 2', insight:'resolver um sistema não é resolver uma linha: o mesmo par precisa satisfazer todas as condições.', readouts:x=>{const y=10-x; return [{label:'y pela primeira equação',value:n(y)},{label:'x − y',value:n(x-y)},{label:'Satisfaz as duas?',value:x-y===2?'sim — (6, 4)':'não',pivot:true}]} },
  matrizes: { id:'matrizes', name:'Somar matrizes é preservar cada posição', question:'Ajuste o valor na posição (2, 2) de A e some elementos correspondentes.', control:{label:'a₂₂',description:'elemento da segunda linha e coluna de A',min:-2,max:6,step:1,initial:5}, formula:'A + B = [aᵢⱼ + bᵢⱼ]', insight:'soma de matrizes exige dimensões iguais porque cada elemento precisa de um correspondente.', readouts:a=>[{label:'A₂₂',value:n(a)},{label:'B₂₂',value:'2'},{label:'(A + B)₂₂',value:n(a+2),pivot:true}] },
  produto: { id:'produto', name:'Linha por coluna produz cada entrada', question:'Altere o primeiro termo da linha de A e acompanhe o produto escalar com a coluna de B.', control:{label:'a₁₁',description:'primeiro termo da linha de A',min:-2,max:5,step:1,initial:1}, formula:'(AB)ᵢⱼ = Σ aᵢₖbₖⱼ', insight:'a ordem importa: a linha da primeira matriz encontra a coluna da segunda; trocar A e B muda as combinações.', readouts:a=>[{label:'Linha de A',value:`(${n(a)}, 2)`},{label:'Coluna de B',value:'(5, 7)'},{label:'Entrada (1, 1)',value:n(a*5+14),pivot:true}] },
  determinante: { id:'determinante', name:'O determinante mede se a matriz colapsa o plano', question:'Mude c em [[2, 3], [c, 5]] e acompanhe ad − bc.', control:{label:'c',description:'elemento inferior esquerdo da matriz',min:0,max:5,step:1,initial:4}, formula:'det(A) = ad − bc', insight:'determinante diferente de zero preserva duas dimensões e permite inversa; zero colapsa a área.', readouts:c=>{const d=10-3*c;return [{label:'Diagonal principal',value:'10'},{label:'Diagonal secundária',value:n(3*c)},{label:'det(A)',value:n(d),pivot:true},{label:'Matriz invertível?',value:d===0?'não':'sim'}]} },
  discussao: { id:'discussao', name:'Retas contam quantas soluções existem', question:'Troque o caso e classifique o sistema de duas equações lineares.', control:{label:'caso',description:'1: secantes; 2: coincidentes; 3: paralelas',min:1,max:3,step:1,initial:1}, formula:'D ≠ 0: única; D = 0: analisar', insight:'determinante zero não decide sozinho: retas coincidentes têm infinitas soluções; paralelas não têm nenhuma.', readouts:k=>{const label=k===1?'uma solução':k===2?'infinitas soluções':'nenhuma solução';const det=k===1?'−1':'0';return [{label:'Determinante',value:det},{label:'Relação geométrica',value:k===1?'secantes':k===2?'coincidentes':'paralelas'},{label:'Classificação',value:label,pivot:true}]} },
};
