export type QuantitiesConfigId='razao'|'porcentagem'|'decimal'|'inteiros'|'medias';
export interface QRead{label:string;value:string;pivot?:boolean} export interface QConfig{id:QuantitiesConfigId;name:string;question:string;control:{label:string;description:string;min:number;max:number;step:number;initial:number};formula:string;insight:string;readouts(v:number):QRead[]}
const f=(x:number)=>String(Math.round(x*100)/100).replace('.',',').replace('-', '−');
export const QUANTITIES:Record<QuantitiesConfigId,QConfig>={
 razao:{id:'razao',name:'Razão compara por divisão',question:'Altere a parte em uma mistura de 10 partes e observe a razão.',control:{label:'parte',description:'quantidade comparada ao total de 10',min:1,max:9,step:1,initial:4},formula:'razão = parte / total',insight:'razão não é diferença: ela preserva a comparação mesmo quando a escala muda.',readouts:v=>[{label:'Parte',value:f(v)},{label:'Total',value:'10'},{label:'Razão',value:`${v}/10`,pivot:true}]},
 porcentagem:{id:'porcentagem',name:'Porcentagem fixa o todo em 100',question:'Mude a porcentagem e acompanhe as três formas equivalentes.',control:{label:'%',description:'partes a cada 100',min:0,max:100,step:5,initial:30},formula:'p% = p/100 = decimal',insight:'porcentagem, fração centesimal e decimal são a mesma razão escrita de três modos.',readouts:v=>[{label:'Fração',value:`${v}/100`},{label:'Decimal',value:f(v/100)},{label:'Porcentagem',value:`${v}%`,pivot:true}]},
 decimal:{id:'decimal',name:'A posição dá valor ao algarismo',question:'Mude o algarismo 3 e veja o valor posicional em milhares.',control:{label:'dígito',description:'algarismo na casa dos milhares',min:0,max:9,step:1,initial:3},formula:'valor = dígito × 10³',insight:'o mesmo símbolo vale diferente conforme a posição; base 10 organiza potências de dez.',readouts:v=>[{label:'Centenas',value:`${v} × 10²`},{label:'Milhares',value:`${v} × 10³`},{label:'Valor em milhares',value:f(v*1000),pivot:true}]},
 inteiros:{id:'inteiros',name:'Divisão euclidiana separa quociente e resto',question:'Varie o dividendo e decomponha-o ao dividir por 7.',control:{label:'a',description:'inteiro a ser dividido por 7',min:-14,max:28,step:1,initial:23},formula:'a = 7q + r; 0 ≤ r < 7',insight:'o resto não é um detalhe: ele é limitado e torna a decomposição única.',readouts:a=>{const r=((a%7)+7)%7,q=(a-r)/7;return[{label:'Quociente q',value:f(q)},{label:'Resto r',value:f(r)},{label:'Reconstrução',value:`7·${q} + ${r} = ${a}`,pivot:true}]}},
 medias:{id:'medias',name:'Peso muda a influência de cada valor',question:'Mude o peso da segunda nota e compare a média ponderada.',control:{label:'peso 2',description:'peso atribuído à nota 8',min:1,max:5,step:1,initial:3},formula:'M = Σ(xᵢpᵢ) / Σpᵢ',insight:'média ponderada não é média simples: valores com maior peso participam mais do resultado.',readouts:p=>{const m=(6+8*p)/(1+p);return[{label:'Nota 6, peso 1',value:'6'},{label:'Nota 8, peso',value:f(p)},{label:'Média ponderada',value:f(m),pivot:true}]}},
};
