export type RemainingId='fila'|'grupo'|'prob'|'eventos'|'estatistica'|'trig-poligonos'|'trig-outras'|'espaco'|'conicas'|'composicao'|'bijeção';export interface R{label:string;value:string;pivot?:boolean}export interface C{id:RemainingId;name:string;question:string;control:{label:string;description:string;min:number;max:number;step:number;initial:number};formula:string;insight:string;readouts(v:number):R[]}
const f=(x:number)=>String(Math.round(x*100)/100).replace('.',',');
export const REMAINING:Record<RemainingId,C>={
 fila:{id:'fila',name:'Na fila, trocar a ordem cria outro arranjo',question:'Escolha quantas pessoas ocuparão posições ordenadas.',control:{label:'n',description:'pessoas em ordem',min:1,max:6,step:1,initial:4},formula:'P(n) = n!',insight:'permutação conta posições: ABC e BAC são resultados distintos.',readouts:n=>[{label:'Posições',value:f(n)},{label:'Arranjos',value:f([1,1,2,6,24,120,720][n]),pivot:true}]},
 grupo:{id:'grupo',name:'No grupo, ordem não cria outro conjunto',question:'Escolha quantas pessoas retirar de um universo de 6.',control:{label:'k',description:'pessoas escolhidas',min:1,max:5,step:1,initial:3},formula:'C(6,k) = 6! / k!(6−k)!',insight:'combinação esquece a ordem: ABC e BAC formam o mesmo grupo.',readouts:k=>[{label:'Universo',value:'6'},{label:'Escolhidas',value:f(k)},{label:'Grupos',value:f([0,6,15,20,15,6][k]),pivot:true}]},
 prob:{id:'prob',name:'União soma e corrige a interseção',question:'Mude a sobreposição entre A e B em 10 resultados equiprováveis.',control:{label:'A ∩ B',description:'resultados compartilhados',min:0,max:3,step:1,initial:1},formula:'P(A∪B)=P(A)+P(B)−P(A∩B)',insight:'somar probabilidades sem descontar a interseção conta os casos compartilhados duas vezes.',readouts:i=>[{label:'P(A)',value:'0,4'},{label:'P(B)',value:'0,3'},{label:'P(A ∪ B)',value:f(.7-i/10),pivot:true}]},
 eventos:{id:'eventos',name:'Disjunto não é sinônimo de independente',question:'Altere o caso e compare interseção e produto.',control:{label:'caso',description:'1: disjuntos; 2: independentes',min:1,max:2,step:1,initial:1},formula:'disjuntos: P(A∩B)=0; independentes: P(A∩B)=P(A)P(B)',insight:'eventos independentes podem acontecer juntos; eventos disjuntos não podem.',readouts:v=>[{label:'P(A ∩ B)',value:v===1?'0':'0,25'},{label:'Relação',value:v===1?'disjuntos':'independentes',pivot:true}]},
 estatistica:{id:'estatistica',name:'Distribuição revela mais que um único resumo',question:'Desloque um valor extremo e compare média e mediana.',control:{label:'extremo',description:'maior valor da amostra 2, 4, 4, 5, x',min:6,max:20,step:1,initial:15},formula:'média = soma / n; mediana = valor central',insight:'a média sente valores extremos; a mediana descreve o centro ordenado com outra sensibilidade.',readouts:x=>[{label:'Média',value:f((15+x)/5)},{label:'Mediana',value:'4'},{label:'Amplitude',value:f(x-2),pivot:true}]},
 'trig-poligonos':{id:'trig-poligonos',name:'Lei dos senos liga lado ao ângulo oposto',question:'Mude o raio circunscrito e observe a razão comum.',control:{label:'R',description:'raio da circunferência circunscrita',min:1,max:8,step:1,initial:5},formula:'a/sen A = b/sen B = c/sen C = 2R',insight:'em qualquer triângulo, cada lado acompanha o seno do ângulo oposto pela mesma razão.',readouts:r=>[{label:'2R',value:f(2*r),pivot:true},{label:'Triângulo',value:'não precisa ser retângulo'}]},
 'trig-outras':{id:'trig-outras',name:'Tangente é uma razão entre seno e cosseno',question:'Mude θ e compare a inclinação com tan θ.',control:{label:'θ',description:'ângulo agudo em graus',min:15,max:75,step:15,initial:45},formula:'tan θ = sen θ / cos θ',insight:'tangente mede inclinação; ela cresce quando o cosseno se aproxima de zero.',readouts:d=>{const t=Math.tan(d*Math.PI/180);return[{label:'θ',value:`${d}°`},{label:'tan θ',value:f(t),pivot:true}]}},
 espaco:{id:'espaco',name:'No espaço, retas podem não se encontrar',question:'Troque a posição relativa de duas retas espaciais.',control:{label:'caso',description:'1: paralelas; 2: concorrentes; 3: reversas',min:1,max:3,step:1,initial:3},formula:'paralelas | concorrentes | reversas',insight:'retas reversas não são paralelas nem concorrentes: pertencem a planos distintos.',readouts:v=>[{label:'Relação',value:['','paralelas','concorrentes','reversas'][v],pivot:true}]},
 conicas:{id:'conicas',name:'O corte do cone decide a cônica',question:'Mude a inclinação do plano de corte.',control:{label:'inclinação',description:'1: transversal; 2: paralela à geratriz; 3: perpendicular',min:1,max:3,step:1,initial:1},formula:'corte de cone duplo',insight:'a mesma superfície cônica produz elipse, parábola ou hipérbole conforme o plano.',readouts:v=>[{label:'Cônica',value:['','hipérbole','parábola','elipse'][v],pivot:true}]},
 composicao:{id:'composicao',name:'Compor é aplicar em ordem',question:'Mude x em g(x)=x+1 e f(u)=2u.',control:{label:'x',description:'entrada da composição',min:-3,max:6,step:1,initial:2},formula:'(f∘g)(x) = f(g(x))',insight:'a ordem é parte da função composta: f∘g geralmente difere de g∘f.',readouts:x=>[{label:'g(x)',value:f(x+1)},{label:'f(g(x))',value:f(2*(x+1)),pivot:true}]},
 bijeção:{id:'bijeção',name:'Bijeção emparelha domínio e contradomínio',question:'Mude o número de imagens ocupadas por quatro elementos do domínio.',control:{label:'imagens',description:'elementos do contradomínio alcançados',min:2,max:4,step:1,initial:4},formula:'injetora + sobrejetora = bijetora',insight:'bijetora não repete imagem nem deixa elemento do contradomínio sem par.',readouts:v=>[{label:'Injetora?',value:v===4?'sim':'não'},{label:'Sobrejetora?',value:v===4?'sim':'não'},{label:'Bijetora?',value:v===4?'sim':'não',pivot:true}]},
};
