import type { OrganicCase } from './organicSpatial';

export interface SpatialChapterLesson { title: string; kind: 'organic'|'reaction'|'water'|'chromatin'|'polymer'; cases?: OrganicCase[]; note: string; }
export const SPATIAL_CHAPTER_LESSONS: Record<string, SpatialChapterLesson> = {
  'summary-quimica-introducao-a-quimica-organica': {title:'Carbono: cadeia normal e ramificada',kind:'organic',cases:['propane','branched'],note:'Escolha a cadeia e confira a tetravalência. Ramo não é heteroátomo; C1, C2… são referências do desenho, não a numeração IUPAC.'},
  'summary-quimica-nomenclatura-de-compostos-organicos': {title:'Conte a cadeia principal ao girar',kind:'organic',cases:['propane','butane','branched'],note:'Propano e butano diferem no número de carbonos; 2-metilpropano tem cadeia principal de três e um ramo no C2. Os índices do desenho apenas identificam átomos.'},
  'summary-quimica-nomenclatura-de-compostos-organicos-oxigenados-e-nitrogenados': {title:'Nome e conectividade do grupo funcional',kind:'organic',cases:['ethanol','ethanal','acetone','acid','ether','amine'],note:'Compare sufixos e conectividade: -ol, -al, -ona, ácido -oico, éter e amina. Apenas girar uma molécula não muda seu nome.'},
  'summary-quimica-reconhecimento-de-funcoes-organicas-e-algumas-de-suas-propriedades': {title:'O grupo funcional depende dos vizinhos',kind:'organic',cases:['ether','ethanol','ethanal','acetone','acid','amine'],note:'O mesmo elemento O aparece em funções distintas; confira C−O−C, C−OH e C=O. O−H é explícito para distinguir doador de ligação de hidrogênio; nenhum ponto de ebulição é calculado.'},
  'summary-quimica-alcoois': {title:'O carbono do OH define o grau do álcool',kind:'organic',cases:['ethanol','secondary','tertiary'],note:'Etanol é primário, propan-2-ol secundário e 2-metilpropan-2-ol terciário. Conte os carbonos diretamente ligados ao carbono da hidroxila, não o total da molécula.'},
  'summary-quimica-interpretando-reacoes-organicas': {title:'Adição: compare reagente e produto',kind:'reaction',cases:['ethene','ethane'],note:'Exemplo: C₂H₄ + H₂ → C₂H₆, hidrogenação catalítica. Dupla vira simples e cada C recebe um H. H ligados a C e catalisador omitidos; são dois estados estáveis, não uma simulação do mecanismo nem da velocidade da reação.'},
  'summary-quimica-reacoes-de-substituicao': {title:'Substituição: troca de grupo sem trocar a cadeia',kind:'reaction',cases:['bromoethane','ethanol'],note:'Exemplo: bromoetano + OH⁻ → etanol + Br⁻, em condições adequadas para substituição nucleofílica. Mostra apenas o substrato e o produto orgânico; reagente OH⁻ e Br⁻ livre omitidos. Não generaliza este mecanismo a substituições aromáticas ou radicalares.'},
  'summary-quimica-reacoes-de-oxidacao-em-hidrocarbonetos': {title:'Oxidação branda de uma dupla',kind:'reaction',cases:['ethene','glycol'],note:'Exemplo: eteno → etano-1,2-diol por KMnO₄ diluído, frio, em meio adequado. Carbonos preservados e dois grupos OH adicionados; dupla vira simples. Oxidante e subprodutos omitidos. Não representa combustão nem clivagem oxidativa; não é equação balanceada.'},
  'summary-quimica-polimeros': {title:'Unidades repetitivas formam uma cadeia',kind:'polymer',note:'Fragmento de polietileno derivado do eteno; cada unidade contribui com dois C, e o esqueleto tem ligações simples. Traços nas extremidades indicam continuação, não átomos extras. Crescimento é uma ilustração finita; iniciação, radicais e condições industriais omitidos.'},
  'summary-quimica-interacoes-intermoleculares': {title:'Entre moléculas: O−H···O',kind:'water',note:'Duas moléculas de água, com 104,5° em cada uma. Traço descontínuo liga H de uma a O da outra; não é uma ligação covalente adicional. Separação qualitativa, sem cálculo de energia ou temperatura; não cobre todos os tipos de interação.'},
  'summary-biologia-composicao-quimica-celular-compostos-inorganicos': {title:'Água: geometria angular e coesão',kind:'water',note:'A geometria angular e a polaridade da água favorecem ligações de hidrogênio entre moléculas. Compare ligação O−H intramolecular e interação H···O intermolecular. Esquema parcial: não representa todos os sais minerais nem prevê solubilidade universal.'},
  'summary-biologia-nucleo-celular': {title:'Cromatina: o mesmo DNA em outra organização',kind:'chromatin',note:'Oito núcleos de histonas, com segmentos de DNA enrolados, em um colar ilustrativo. Condensar reorganiza o mesmo material; não duplica DNA nem converte um nucleossomo em um cromossomo inteiro. Fio azul tracejado é DNA, não ligação de hidrogênio. Modelo não representa a organização exata de todas as fibras de cromatina, a carioteca ou os poros.'},
};
