export type ThermoId = 'gas-work' | 'first-law' | 'carnot';
export interface ThermoReadout { label: string; value: string; pivot?: boolean }
export interface ThermoConfig { id: ThermoId; name: string; question: string; control: { label: string; description: string; min: number; max: number; step: number; initial: number }; formula: string; insight: string; readouts(value: number): ThermoReadout[] }
const value = (n: number) => String(Math.round(n * 10) / 10).replace('.', ',');
export const THERMO: Record<ThermoId, ThermoConfig> = {
  'gas-work': { id:'gas-work', name:'Gás realiza trabalho ao expandir', question:'Mude a variação de volume sob pressão constante de 3 kPa.', control:{label:'ΔV',description:'variação de volume em L',min:-4,max:8,step:1,initial:4}, formula:'W = PΔV', insight:'a área sob a curva P×V mede trabalho; expansão e compressão têm sinais opostos.', readouts:v=>[{label:'Pressão',value:'3 kPa'},{label:'Trabalho do gás',value:`${3*v} J`,pivot:true}] },
  'first-law': { id:'first-law', name:'Calor e trabalho mudam a energia interna', question:'Mude o trabalho realizado pelo gás após receber 12 J de calor.', control:{label:'W',description:'trabalho realizado pelo gás em J',min:-4,max:16,step:1,initial:5}, formula:'ΔU = Q − W', insight:'calor recebido aumenta energia interna; trabalho feito pelo sistema a reduz.', readouts:w=>[{label:'Calor Q',value:'12 J'},{label:'ΔU',value:`${12-w} J`,pivot:true}] },
  carnot: { id:'carnot', name:'Máquina térmica transforma parte do calor em trabalho', question:'Mude o calor rejeitado à fonte fria após receber 20 J da fonte quente.', control:{label:'Qc',description:'calor rejeitado em J',min:1,max:18,step:1,initial:8}, formula:'η = W/Qh = 1 − Qc/Qh', insight:'uma máquina cíclica não converte todo calor em trabalho: parte precisa seguir à fonte fria.', readouts:qc=>[{label:'Q quente',value:'20 J'},{label:'Trabalho W',value:`${20-qc} J`},{label:'Rendimento',value:`${value((20-qc)/20*100)}%`,pivot:true}] },
};
