/**
 * THROWAWAY UI PROTOTYPE — validates the approved Núcleo Instrumental
 * direction across every app route. Run `npm run dev`, then open
 * /prototype/nucleo-instrumental?screen=hoje. State is intentionally local.
 */
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import {
  Activity, ArrowLeft, ArrowRight, Atom, BarChart3, BookOpen, Brain, Calendar,
  CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck, Compass, FileText,
  FlaskConical, Headphones, Layers3, Library, Link2, ListTodo, Map, Menu,
  MessageCircleQuestion, NotebookPen, PenLine, Play, Repeat2, Settings2,
  Sparkles, Stethoscope, Target, TrendingUp, UserRound, type LucideIcon,
} from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import './nucleo-instrumental-prototype.css';

type Kind = 'decision' | 'practice' | 'library' | 'analysis' | 'account' | 'admin';
type Screen = { key: string; label: string; title: string; summary: string; kind: Kind; icon: LucideIcon; subject: string; topic: string; action: string };

const SCREENS: Screen[] = [
  { key: 'hoje', label: 'Hoje', title: 'Comece onde sua aprovação ganha mais força.', summary: 'Uma recomendação explicável transforma sinais do seu histórico na próxima decisão.', kind: 'decision', icon: Calendar, subject: 'Matemática', topic: 'Geometria analítica', action: 'Iniciar bloco · 40 min' },
  { key: 'diagnostico', label: 'Diagnóstico', title: 'Veja a estrutura antes de acelerar.', summary: 'Uma leitura inicial revela os temas que sustentam mais evolução.', kind: 'analysis', icon: Stethoscope, subject: 'Física', topic: 'Óptica geométrica', action: 'Continuar diagnóstico' },
  { key: 'plano', label: 'Plano', title: 'Sua trajetória, em decisões realizáveis.', summary: 'O plano se reorganiza à medida que suas evidências mudam.', kind: 'decision', icon: Map, subject: 'Biologia', topic: 'Ecologia', action: 'Ver semana completa' },
  { key: 'agenda', label: 'Agenda', title: 'Tempo protegido para estudar melhor.', summary: 'Disponibilidade, blocos e compromissos no mesmo instrumento.', kind: 'account', icon: Calendar, subject: 'Geografia', topic: 'Climatologia', action: 'Ajustar disponibilidade' },
  { key: 'reta-final', label: 'Reta Final', title: 'Concentre energia no que decide a prova.', summary: 'Uma camada de priorização para as últimas semanas.', kind: 'decision', icon: Target, subject: 'História', topic: 'Guerra Fria', action: 'Abrir estratégia final' },
  { key: 'recuperacao', label: 'Recuperação', title: 'Recupere o atraso sem perder o eixo.', summary: 'O sistema preserva o que importa e reposiciona o restante.', kind: 'decision', icon: ListTodo, subject: 'Química', topic: 'Equilíbrio químico', action: 'Recalcular recuperação' },
  { key: 'sessao', label: 'Sessão de Estudo', title: 'Praticar com precisão, não por inércia.', summary: 'Questões graduadas, tempo visível e feedback no ponto certo.', kind: 'practice', icon: Play, subject: 'Matemática', topic: 'Funções', action: 'Começar sessão' },
  { key: 'questoes', label: 'Questões', title: 'Transforme tentativa em evidência.', summary: 'Cada resposta atualiza a leitura do tópico e da estratégia.', kind: 'practice', icon: ClipboardCheck, subject: 'Física', topic: 'Mecânica', action: 'Resolver próxima questão' },
  { key: 'resumos', label: 'Resumos', title: 'Repertório que entra em ação.', summary: 'Leitura, recuperação e transferência conectadas ao seu plano.', kind: 'library', icon: Library, subject: 'Português', topic: 'Interpretação de texto', action: 'Explorar resumos' },
  { key: 'revisoes', label: 'Revisões', title: 'Volte antes que o conhecimento se afaste.', summary: 'Janelas de revisão organizadas por urgência e confiança.', kind: 'practice', icon: Repeat2, subject: 'Biologia', topic: 'Genética', action: 'Iniciar revisão' },
  { key: 'flashcards', label: 'Flashcards', title: 'Memória ativa, feedback imediato.', summary: 'Cartões aparecem no intervalo em que mais ajudam.', kind: 'practice', icon: Layers3, subject: 'Química', topic: 'Estequiometria', action: 'Abrir cartões' },
  { key: 'obras-obrigatorias', label: 'Flashcards de Obras', title: 'As obras ficam disponíveis na hora da prova.', summary: 'Referências, personagens, forma e contexto em recuperação ativa.', kind: 'practice', icon: BookOpen, subject: 'Literatura', topic: 'Romantismo brasileiro', action: 'Revisar obra' },
  { key: 'obras', label: 'Dossiês de Obras', title: 'Ler obra é enxergar suas camadas.', summary: 'Dossiês conectam construção formal, contexto e repertório.', kind: 'library', icon: BookOpen, subject: 'Literatura', topic: 'Memórias Póstumas', action: 'Abrir dossiê' },
  { key: 'erros', label: 'Caderno de Erros', title: 'Erros viram rotas de recuperação.', summary: 'O primeiro elo ausente é mais útil que uma correção genérica.', kind: 'analysis', icon: NotebookPen, subject: 'Português', topic: 'Sintaxe', action: 'Retomar conexão' },
  { key: 'podcast', label: 'Podcast Crivo', title: 'Repertório para ouvir com intenção.', summary: 'Episódios conectados a temas que pedem contexto agora.', kind: 'library', icon: Headphones, subject: 'Atualidades', topic: 'Geopolítica', action: 'Ouvir episódio' },
  { key: 'tutor', label: 'Tutor Socrático', title: 'Uma pergunta que destrava o raciocínio.', summary: 'O tutor preserva seu caminho e pede o próximo passo possível.', kind: 'library', icon: Brain, subject: 'Filosofia', topic: 'Ética', action: 'Conversar com tutor' },
  { key: 'laboratorio', label: 'Laboratório', title: 'Métodos que você consegue repetir.', summary: 'Experimentos de estudo para descobrir o que funciona para você.', kind: 'library', icon: FlaskConical, subject: 'Biologia', topic: 'Fisiologia', action: 'Testar método' },
  { key: 'treino-2a-fase', label: 'Treino de 2ª Fase', title: 'Construa resposta, não apenas resultado.', summary: 'Treino discursivo com critérios e encadeamento explícitos.', kind: 'practice', icon: FileText, subject: 'História', topic: 'Brasil República', action: 'Iniciar treino' },
  { key: 'redacao', label: 'Redação', title: 'Argumento tem arquitetura.', summary: 'Tese, repertório e coesão se conectam em um texto defendível.', kind: 'practice', icon: PenLine, subject: 'Redação', topic: 'Coesão argumentativa', action: 'Escrever agora' },
  { key: 'estrategias', label: 'Estratégias', title: 'Escolha a ferramenta certa para a questão.', summary: 'Heurísticas visíveis para resolver sob pressão.', kind: 'library', icon: Compass, subject: 'Matemática', topic: 'Probabilidade', action: 'Ver estratégia' },
  { key: 'evolucao', label: 'Evolução', title: 'Evolução é uma trajetória, não um número solto.', summary: 'Domínio, consistência e confiança mostram o próximo ajuste.', kind: 'analysis', icon: TrendingUp, subject: 'Geografia', topic: 'Urbanização', action: 'Ver análise completa' },
  { key: 'prioridades', label: 'Prioridades', title: 'Cada vestibular muda o peso da decisão.', summary: 'Incidência e evidência pessoal se encontram na mesma vista.', kind: 'analysis', icon: Sparkles, subject: 'Atualidades', topic: 'Economia', action: 'Comparar provas' },
  { key: 'conexoes', label: 'Conexões', title: 'Sua infraestrutura de estudo, sob controle.', summary: 'Integrações claras, estados explicáveis e confirmação segura.', kind: 'account', icon: Link2, subject: 'Física', topic: 'Eletricidade', action: 'Gerenciar conexão' },
  { key: 'perfil', label: 'Perfil', title: 'O plano começa com seus limites reais.', summary: 'Meta, disponibilidade e preferências com leitura serena.', kind: 'account', icon: UserRound, subject: 'Literatura', topic: 'Análise literária', action: 'Editar perfil' },
  { key: 'admin', label: 'Administração', title: 'Pulso da plataforma, com sinal e contexto.', summary: 'Atividade, qualidade e filas operacionais em uma leitura única.', kind: 'admin', icon: Settings2, subject: 'Atualidades', topic: 'Sinais de atividade', action: 'Abrir operação' },
  { key: 'admin-obras', label: 'Admin Obras', title: 'Catálogo literário com integridade editorial.', summary: 'Obras, fontes e cobertura em um fluxo controlado.', kind: 'admin', icon: BookOpen, subject: 'Literatura', topic: 'Catálogo de obras', action: 'Gerenciar obras' },
  { key: 'admin-conteudo', label: 'Admin Conteúdo', title: 'Conteúdo pronto para entrar em circulação.', summary: 'Fila, qualidade e publicação no mesmo painel operacional.', kind: 'admin', icon: Activity, subject: 'Química', topic: 'Pipeline de conteúdo', action: 'Abrir fila' },
];

const PALETTES: Record<string, { primary: string; secondary: string; wash: string; family: string }> = {
  Matemática: { primary: '#81a9ff', secondary: '#d9b583', wash: 'rgba(57,105,211,.35)', family: 'grid' }, Física: { primary: '#75a2ff', secondary: '#e7c05f', wash: 'rgba(39,92,200,.37)', family: 'wave' }, Química: { primary: '#efbf61', secondary: '#81b179', wash: 'rgba(175,110,45,.34)', family: 'bond' }, Biologia: { primary: '#86dca5', secondary: '#e69172', wash: 'rgba(38,130,78,.36)', family: 'organic' }, Português: { primary: '#e08391', secondary: '#d9b583', wash: 'rgba(139,47,70,.36)', family: 'type' }, Literatura: { primary: '#d5b184', secondary: '#a779ca', wash: 'rgba(110,55,96,.33)', family: 'type' }, História: { primary: '#df7783', secondary: '#9bbce2', wash: 'rgba(136,55,52,.32)', family: 'poles' }, Geografia: { primary: '#aac86d', secondary: '#d89c58', wash: 'rgba(74,105,57,.36)', family: 'topo' }, Redação: { primary: '#e69b64', secondary: '#d7665d', wash: 'rgba(130,66,40,.34)', family: 'type' }, Atualidades: { primary: '#e3ad60', secondary: '#8abbdc', wash: 'rgba(45,97,130,.35)', family: 'signal' }, Filosofia: { primary: '#b69bdd', secondary: '#d9b583', wash: 'rgba(88,57,131,.32)', family: 'poles' },
};

function Artifact({ family, primary, secondary }: { family: string; primary: string; secondary: string }) {
  return <div className={`ni-artifact ni-artifact--${family}`} style={{ '--p': primary, '--s': secondary } as React.CSSProperties}><i /><b /><em /><span /></div>;
}

function PrototypeSwitcher({ current, onChange }: { current: number; onChange: (index: number) => void }) {
  const navigate = useNavigate();
  const screen = SCREENS[current];
  const move = (delta: number) => onChange((current + delta + SCREENS.length) % SCREENS.length);
  useEffect(() => {
    const handler = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement;
      if (target.matches('input,textarea,[contenteditable=true]')) return;
      if (event.key === 'ArrowLeft') move(-1);
      if (event.key === 'ArrowRight') move(1);
    };
    window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler);
  });
  return <div className="ni-switcher" aria-label="Controle do protótipo"><button onClick={() => move(-1)} aria-label="Tela anterior"><ChevronLeft /></button><span><b>{current + 1}/{SCREENS.length}</b> · {screen.label}</span><button onClick={() => move(1)} aria-label="Próxima tela"><ChevronRight /></button><button className="ni-exit" onClick={() => navigate('/')} aria-label="Sair do protótipo">×</button></div>;
}

export default function NucleoInstrumentalPrototype() {
  const [params, setParams] = useSearchParams();
  const initial = Math.max(0, SCREENS.findIndex((screen) => screen.key === params.get('screen')));
  const [index, setIndex] = useState(initial);
  const [expanded, setExpanded] = useState(false);
  const [details, setDetails] = useState(false);
  const reduceMotion = useReducedMotion();
  const screen = SCREENS[index];
  const palette = PALETTES[screen.subject] ?? PALETTES.Matemática;
  const setScreen = (next: number) => { setIndex(next); setParams({ screen: SCREENS[next].key }); setDetails(false); };
  const content = useMemo(() => screen.kind === 'decision' ? <Decision screen={screen} details={details} setDetails={setDetails} /> : screen.kind === 'practice' ? <Practice screen={screen} /> : screen.kind === 'library' ? <LibraryView screen={screen} /> : screen.kind === 'analysis' ? <Analysis screen={screen} /> : screen.kind === 'admin' ? <Admin screen={screen} /> : <Account screen={screen} />, [screen, details]);
  return <div className="ni-prototype" style={{ '--primary': palette.primary, '--secondary': palette.secondary, '--wash': palette.wash } as React.CSSProperties} data-family={palette.family}>
    <aside className={`ni-rail ${expanded ? 'is-expanded' : ''}`}><button className="ni-mark" aria-label="Crivo">◉</button><div className="ni-rail-scroll">{SCREENS.map((item, itemIndex) => { const Icon = item.icon; return <button key={item.key} onClick={() => setScreen(itemIndex)} className={item.key === screen.key ? 'active' : ''} title={item.label}><span className="ni-icon-depth"><Icon /></span>{expanded && <b>{item.label}</b>}</button>; })}</div><button onClick={() => setExpanded(!expanded)} className="ni-rail-toggle" aria-label={expanded ? 'Recolher áreas' : 'Expandir áreas'}><Menu /></button></aside>
    <div className="ni-page"><header className="ni-top"><div className="ni-mobile-mark">◉</div><strong>Crivo</strong><nav aria-label="Áreas principais"><span className={screen.kind === 'decision' ? 'active' : ''}>Hoje</span><span>Plano</span><span className={screen.kind === 'practice' ? 'active' : ''}>Estudar</span><span className={screen.kind === 'analysis' ? 'active' : ''}>Análises</span></nav><span className="ni-prototype-badge">PROTÓTIPO · sem dados reais</span><div className="ni-avatar">AJ</div></header>
      <main className="ni-main"><div className="ni-route"><span>{screen.kind.toUpperCase()}</span><i /> <span>{screen.subject}</span><i /> <b>{screen.topic}</b></div><div className="ni-title"><div><h1>{screen.title}</h1><p>{screen.summary}</p></div><div className="ni-state"><i /> perfil {palette.family} · motion ativo</div></div><div className="ni-subjects">{Object.keys(PALETTES).slice(0, 10).map((subject) => <button key={subject} onClick={() => { const next = SCREENS.findIndex((candidate) => candidate.subject === subject); if (next >= 0) setScreen(next); }} className={subject === screen.subject ? 'active' : ''}>{subject}</button>)}</div>
        <AnimatePresence mode="wait"><motion.div key={screen.key} className="ni-view" initial={reduceMotion ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={reduceMotion ? undefined : { opacity: 0, y: -12 }} transition={{ type: 'spring', stiffness: palette.family === 'grid' ? 260 : 140, damping: palette.family === 'poles' ? 12 : 20 }}>{content}</motion.div></AnimatePresence>
      </main></div><PrototypeSwitcher current={index} onChange={setScreen} />
  </div>;
}

function Decision({ screen, details, setDetails }: { screen: Screen; details: boolean; setDetails: (open: boolean) => void }) { return <><section className="ni-grid ni-grid--hero"><motion.article className="ni-panel ni-decision" whileHover={{ y: -3 }}><span className="ni-kicker">Decisão recomendada · 01</span><h2>{screen.topic} antes da prova.</h2><p>Recorrência alta, domínio instável e uma janela real de estudo se alinham neste bloco.</p><button className="ni-primary"><Play />{screen.action}</button><button className="ni-link" onClick={() => setDetails(!details)}>Por que esta decisão? {details ? '↑' : '↓'}</button><Artifact family={(PALETTES[screen.subject] ?? PALETTES.Matemática).family} primary={(PALETTES[screen.subject] ?? PALETTES.Matemática).primary} secondary={(PALETTES[screen.subject] ?? PALETTES.Matemática).secondary} /><div className="ni-metrics"><Metric label="domínio" value="62%" bar /><Metric label="confiança" value="média" /><Metric label="urgência" value="alta" warn /><Metric label="recorrência" value="8,7" /></div></motion.article><aside className="ni-panel ni-trajectory"><span className="ni-kicker">Trajetória semanal</span><h3>Você está em ritmo.</h3><div className="ni-chart"><i /><b /><em /><strong /></div><p><span>+12%</span> de consistência na semana</p><ul><li>Revisões adaptativas <b>3</b></li><li>Erros para retomar <b>8</b></li><li>Próxima sessão <b>14:00</b></li></ul></aside></section>{details && <motion.section className="ni-panel ni-bay" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}><span className="ni-kicker">Baía de análise</span><h3>Os sinais que formaram a recomendação.</h3><div>{['incidência Fuvest', 'domínio observado', 'janela de revisão', 'tempo disponível'].map((factor, i) => <p key={factor}><i /><span>{factor}</span><b>0.{91 - i * 8}</b></p>)}</div></motion.section>}<section className="ni-card-row"><Mini title="Sessão" text="Questões, tempo e feedback." icon={Play} /><Mini title="Biblioteca" text="Materiais ligados ao tópico." icon={Library} /><Mini title="Próximo passo" text="Proteja amanhã às 14:00." icon={ArrowRight} /></section></> }
function Practice({ screen }: { screen: Screen }) { return <section className="ni-grid ni-grid--practice"><article className="ni-panel ni-workspace"><span className="ni-kicker">{screen.topic} · sequência 02/05</span><h2>Qual é o próximo passo do raciocínio?</h2><p>O feedback só aparece depois da sua tentativa.</p><div className="ni-question">Uma reta passa pelos pontos A e B. Qual representação mantém a relação entre inclinação e intercepto?</div><div className="ni-options">{['y = ax + b', 'x² + y² = r²', 'f(x) = Δy / Δx'].map((option) => <button key={option}>{option}</button>)}</div><button className="ni-primary"><CheckCircle2 />{screen.action}</button></article><aside className="ni-panel ni-session-side"><span className="ni-kicker">Instrumentos</span><div className="ni-timer">24:18</div><Metric label="precisão" value="4 / 5" bar /><Metric label="ritmo" value="estável" /><div className="ni-stack"><span /><span /><span /></div><p>O material reage ao perfil do tópico, mas a resposta continua o centro da tela.</p></aside></section> }
function LibraryView({ screen }: { screen: Screen }) { return <section className="ni-grid ni-grid--library"><article className="ni-panel ni-library-lead"><span className="ni-kicker">Coleção conectada</span><h2>{screen.topic} em camadas.</h2><p>Comece por um objeto editorial e avance para recuperação e aplicação.</p><div className="ni-book"><i /><b>{screen.subject}</b><span /></div><button className="ni-primary"><BookOpen />{screen.action}</button></article><div className="ni-library-list">{['Visão geral essencial', 'Recuperação ativa', 'Aplicação em questão', 'Conexões de repertório'].map((item, i) => <motion.article className="ni-panel" key={item} whileHover={{ x: 4 }}><span>0{i + 1}</span><h3>{item}</h3><p>Um passo curto, claro e ligado ao que você precisa agora.</p><ArrowRight /></motion.article>)}</div></section> }
function Analysis({ screen }: { screen: Screen }) { return <><section className="ni-card-row"><MetricCard title="Domínio consolidado" value="62%" /><MetricCard title="Confiança calibrada" value="média" /><MetricCard title="Prioridade na prova" value="alta" /></section><section className="ni-grid ni-grid--analysis"><article className="ni-panel ni-analysis-map"><span className="ni-kicker">Mapa de evidências</span><h2>{screen.topic} pede ajuste.</h2><div className="ni-map"><i /><i /><i /><i /><b /></div><p>O mapa combina recorrência, desempenho e intervalo de revisão.</p></article><aside className="ni-panel ni-analysis-list"><span className="ni-kicker">Leituras acionáveis</span>{['Consolidar base', 'Retomar erro recorrente', 'Simular sob tempo'].map((item, i) => <button key={item}><span>0{i + 1}</span>{item}<ArrowRight /></button>)}<button className="ni-primary"><BarChart3 />{screen.action}</button></aside></section></> }
function Account({ screen }: { screen: Screen }) { return <section className="ni-grid ni-grid--account"><article className="ni-panel"><span className="ni-kicker">Preferências e infraestrutura</span><h2>{screen.title}</h2><p>{screen.summary}</p><div className="ni-settings">{['Disponibilidade semanal', 'Meta de estudo', 'Notificações úteis', 'Preferência de movimento'].map((item, i) => <div key={item}><span>{item}</span><b>{i === 3 ? 'reduzir quando preciso' : 'configurado'}</b></div>)}</div><button className="ni-primary"><Settings2 />{screen.action}</button></article><aside className="ni-panel ni-account-art"><Artifact family="signal" primary="#81a9ff" secondary="#d9b583" /><p>Estados de conexão, edição e confirmação recebem movimento curto e explícito.</p></aside></section> }
function Admin({ screen }: { screen: Screen }) { return <><section className="ni-card-row"><MetricCard title="Atividade em 24h" value="1.284" /><MetricCard title="Fila de revisão" value="18 itens" /><MetricCard title="Integridade" value="98,7%" /></section><section className="ni-grid ni-grid--admin"><article className="ni-panel"><span className="ni-kicker">Sinal operacional</span><h2>{screen.title}</h2><div className="ni-admin-chart"><i /><i /><i /><i /><i /></div><p>{screen.summary}</p></article><aside className="ni-panel ni-admin-queue"><span className="ni-kicker">Fila priorizada</span>{['Validar fonte', 'Publicar material', 'Revisar cobertura', 'Resolver alerta'].map((item, i) => <button key={item}><b>0{i + 1}</b><span>{item}</span><ArrowRight /></button>)}<button className="ni-primary"><Activity />{screen.action}</button></aside></section></> }
function Metric({ label, value, bar = false, warn = false }: { label: string; value: string; bar?: boolean; warn?: boolean }) { return <div className="ni-metric"><small>{label}</small><b className={warn ? 'warn' : ''}>{value}</b>{bar && <i><span /></i>}</div> }
function MetricCard({ title, value }: { title: string; value: string }) { return <article className="ni-panel ni-metric-card"><span className="ni-kicker">{title}</span><b>{value}</b><i /></article> }
function Mini({ title, text, icon: Icon }: { title: string; text: string; icon: LucideIcon }) { return <motion.article className="ni-panel ni-mini" whileHover={{ y: -3 }}><span className="ni-icon-depth"><Icon /></span><h3>{title}</h3><p>{text}</p></motion.article> }
