import React, { useState } from 'react';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import { STAGE_LABEL } from '../../lib/visualStudy';
import { ALGEBRA_CONFIGS, type AlgebraConfigId } from '../../lib/algebraLab';
import type { BoardProps } from '../visual-boards/types';
import './AlgebraInstrument.css';
function Scene({id,value}:{id:AlgebraConfigId;value:number}) {
  if(id==='fatoracao') return <><text x="160" y="66" textAnchor="middle">x² − 4</text><path className="vs-alg-arrow" d="M75 100 H245"/><text x="160" y="146" textAnchor="middle">(x + 2)(x − 2)</text><rect className="vs-alg-card" x="76" y="176" width="168" height="58" rx="8"/><text x="160" y="212" textAnchor="middle">x = {value} → mesmo valor</text></>;
  if(id==='igualdades') { const yes=value===6; return <><path className="vs-alg-balance" d="M55 190 H265 M160 74 V220 M105 190 L160 112 L215 190"/><text x="107" y="155" textAnchor="middle">√(x+3)</text><text x="213" y="155" textAnchor="middle">x−3</text><text x="160" y="254" textAnchor="middle">x = {value}: {yes?'confere':'não confere'}</text></> }
  if(id==='desigualdades') { const tx=(v:number)=>42+(v+6)*19; return <><line className="vs-alg-axis" x1="36" y1="154" x2="284" y2="154"/>{[-6,-2,3,6].map(n=><text key={n} x={tx(n)} y="178" textAnchor="middle">{n}</text>)}<circle className="vs-alg-open" cx={tx(-2)} cy="154" r="7"/><circle className="vs-alg-open" cx={tx(3)} cy="154" r="7"/><path className="vs-alg-accent" d={`M42 130 H${tx(-2)-9} M${tx(3)+9} 130 H278`}/><circle className="vs-alg-point" cx={tx(value)} cy="154" r="7"/><text x="160" y="232" textAnchor="middle">x &lt; −2 ou x &gt; 3</text></> }
  if(id==='modelagem-linear') return <><rect className="vs-alg-card" x="44" y="88" width="98" height="96" rx="8"/><rect className="vs-alg-card vs-alg-copy" x="178" y="88" width="98" height="96" rx="8"/><text x="93" y="130" textAnchor="middle">x</text><text x="93" y="158" textAnchor="middle">{value}</text><text x="227" y="130" textAnchor="middle">x + 1</text><text x="227" y="158" textAnchor="middle">{value+1}</text><text x="160" y="236" textAnchor="middle">{value} + {value+1} = {2*value+1}</text></>;
  if(id==='modelagem-quadratica') { const vals=Array.from({length:7},(_,x)=>(50-4*x)*(200+30*x)); const max=Math.max(...vals); return <><path className="vs-alg-axis" d="M40 240 H286 M48 244 V54"/>{vals.map((r,x)=>{const px=58+x*34;const py=218-(r-9000)/14;return <circle key={x} className={r===max?'vs-alg-point':'vs-alg-dot'} cx={px} cy={py} r="5"/>})}<path className="vs-alg-accent" d={`M${58+value*34} 240 V${218-(vals[value]-9000)/14}`}/><text x="160" y="272" textAnchor="middle">R({value}) = R${vals[value]}</text></> }
  const c=value; return <><path className="vs-alg-region" d={`M50 250 L50 ${250-c*22} L${50+c*22} 250 Z`}/><path className="vs-alg-accent" d={`M50 ${250-c*22} L${50+c*22} 250`}/><path className="vs-alg-axis" d="M38 250 H282 M50 266 V40"/><text x="214" y="226" textAnchor="middle">x + y ≤ {c}</text><circle className="vs-alg-point" cx="94" cy="206" r="5"/><text x="104" y="204">(2,2)</text></>;
}
function short(t?:string){const s=t?.trim().split(/(?<=[.!?])\s/)[0]??'';return s.length>190?`${s.slice(0,186)}…`:s}
const cond:Record<AlgebraConfigId,string>={fatoracao:'=',igualdades:'x',desigualdades:'sinal','modelagem-linear':'Σ','modelagem-quadratica':'R','inequacoes-plano':'≤'};
export function algebraInstrument(id:AlgebraConfigId){const config=ALGEBRA_CONFIGS[id];return function AlgebraBoard(props:BoardProps){const pair=boardPair(props);const [value,setValue]=useState(config.control.initial);const readings=config.readouts(value);const pivot=readings.find(x=>x.pivot)??readings[0];const first=props.map.nodes[0];const second=props.map.nodes[2]??props.map.nodes.at(-1);return <BoardShell kicker="Laboratório de álgebra" title={config.name} subtitle={config.question} condition={{label:cond[id],value:pivot.value}} ariaLabel={`Instrumento de álgebra: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument vs-algebra-instrument"><svg className="vs-plane vs-algebra" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value}/></svg><p className="vs-instrument-dica">mexa no valor e compare a regra com a consequência</p><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`alg-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{String(value).replace('.',',')}</b></label><input id={`alg-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={e=>setValue(Number(e.target.value))}/></div></div><dl className="vs-plane-readouts">{readings.map(r=><div key={r.label} data-pivot={r.pivot?'true':undefined}><dt>{r.label}</dt><dd>{r.value}</dd></div>)}</dl></div>} left={{label:STAGE_LABEL[first?.stage??'conceito'],headline:first?.label??props.map.title,detail:short(first?.excerpt),formula:config.formula}} right={{label:STAGE_LABEL[second?.stage??'aplicacao'],headline:second?.label??props.map.title,detail:short(second?.excerpt),formula:`${pivot.label} = ${pivot.value}`}} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{label:'Leitura algébrica',general:config.formula,condition:'mostra',reduced:pivot.value}} closing={config.insight}/>}}
