import React, { useState } from 'react';
import { BIOLOGY_INSTRUMENTS, type BiologyInstrumentId } from '../../lib/biologyInstrumentLab';
import { STAGE_LABEL } from '../../lib/visualStudy';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import type { BoardProps } from '../visual-boards/types';

const ink = { stroke: 'var(--vs-ink)', strokeWidth: 3, fill: 'none' };
const red = { stroke: 'var(--vs-burgundy)', strokeWidth: 5, fill: 'none' };
function Scene({ id, value }: { id: BiologyInstrumentId; value: number }) {
  if (id === 'nucleic-acids') return <><path d="M70 55C250 95 70 205 250 245M250 55C70 95 250 205 70 245" {...ink}/>{[75,115,155,195,235].map((y, index) => <path key={y} d={`M${95 + (index % 2) * 25} ${y}H${225 - (index % 2) * 25}`} {...red}/>) }<text x="160" y="285" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>complementaridade preserva a sequência</text></>;
  if (id === 'linkage') return <><path d="M65 85H255M65 215H255" {...ink}/><circle cx="105" cy="85" r="12" fill="var(--vs-burgundy)"/><circle cx={105 + value * 2.5} cy="85" r="12" fill="var(--vs-ink)"/><path d={`M105 120C140 ${150 + value} 180 ${150 - value} ${105 + value * 2.5} 180`} {...red}/><text x="160" y="260" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>{value} cM</text></>;
  if (id === 'circulation') return <><path d="M35 150H105M215 150H285" {...red}/>{Array.from({ length: Math.max(2, Math.round(value)) }, (_, index) => <path key={index} d={`M105 150C140 ${70 + index * 22} 180 ${70 + index * 22} 215 150`} {...ink} strokeWidth="2"/>)}<text x="160" y="270" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>mais área total → menor velocidade</text></>;
  if (id === 'respiration') return <><circle cx="115" cy="145" r="72" fill="var(--vs-paper)" stroke="var(--vs-ink)" strokeWidth="3"/><path d="M187 145H275" {...red}/>{[105,145,185].map((y) => <circle key={y} cx={200 + (value - 40) / 3} cy={y} r="7" fill="var(--vs-burgundy)"/>)}<text x="115" y="152" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>alvéolo</text><text x="235" y="245" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>O₂ segue o gradiente</text></>;
  return <><path d="M160 260C155 210 155 145 160 75" {...ink}/><path d="M160 170C120 150 95 125 75 90M160 145C200 125 225 100 245 65" {...ink}/><circle cx="55" cy="55" r="25" fill="var(--vs-burgundy)" opacity=".8"/><path d={`M160 255Q${160 + value} 160 175 70`} {...red}/><text x="58" y="100" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>luz</text><text x="210" y="285" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>alongamento assimétrico</text></>;
}
function short(text?: string) { const sentence = text?.split(/(?<=[.!?])\s/)[0] ?? ''; return sentence.length > 180 ? `${sentence.slice(0, 176)}…` : sentence; }
export function biologyInstrument(id: BiologyInstrumentId) { const config = BIOLOGY_INSTRUMENTS[id]; return function BiologyBoard(props: BoardProps) { const [value, setValue] = useState(config.control.initial); const readouts = config.readouts(value); const pivot = readouts.find((item) => item.pivot) ?? readouts[0]; const pair = boardPair(props); const first = props.map.nodes[0]; const second = props.map.nodes[2] ?? props.map.nodes.at(-1); return <BoardShell kicker="Laboratório de biologia" title={config.name} subtitle={config.question} condition={{ label: 'Leitura', value: pivot.value }} ariaLabel={`Instrumento de biologia: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value}/></svg><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`biology-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{config.control.display(value)}</b></label><input id={`biology-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={(event) => setValue(Number(event.target.value))}/></div></div><dl className="vs-plane-readouts">{readouts.map((item) => <div key={item.label} data-pivot={item.pivot ? 'true' : undefined}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></div>} left={{ label: STAGE_LABEL[first?.stage ?? 'conceito'], headline: first?.label ?? props.map.title, detail: short(first?.excerpt), formula: config.relation }} right={{ label: STAGE_LABEL[second?.stage ?? 'aplicacao'], headline: second?.label ?? props.map.title, detail: short(second?.excerpt), formula: pivot.value }} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{ label: 'Relação biológica', general: config.relation, condition: 'mostra', reduced: pivot.value }} closing={config.insight}/>; }; }
