import React, { useState } from 'react';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import { STAGE_LABEL } from '../../lib/visualStudy';
import { ELECTRIC, type ElectricId } from '../../lib/electricLab';
import type { BoardProps } from '../visual-boards/types';

const ink = { stroke: 'var(--vs-ink)', strokeWidth: 3, fill: 'none' };
const red = { stroke: 'var(--vs-burgundy)', strokeWidth: 5, fill: 'none' };
function Scene({ id, value }: { id: ElectricId; value: number }) {
  if (id === 'current') return <><path d="M35 150H285" {...ink}/>{[70, 130, 190, 250].map((x) => <circle key={x} cx={x} cy="150" r="9" fill="var(--vs-burgundy)" opacity={Math.max(.25, value / 16)} />)}<text x="160" y="205" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>cargas cruzam a seção</text></>;
  if (id === 'power') return <><rect x="115" y="110" width="90" height="80" rx="10" fill="var(--vs-paper)" stroke="var(--vs-ink)" strokeWidth="3"/><path d="M35 150H110M210 150H285" {...red}/><text x="160" y="158" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>{12 * value} W</text></>;
  if (id === 'resistor') return <><path d="M35 150H90l12-28 16 56 16-56 16 56 16-56 16 28h73" {...ink}/><path d={`M35 220H${35 + value * 20}`} {...red}/><text x="160" y="265" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>mais R → menos i</text></>;
  if (id === 'kirchhoff') return <><path d="M35 150H140M140 150L250 85M140 150L250 215" {...ink}/><circle cx="140" cy="150" r="10" fill="var(--vs-burgundy)"/><text x="80" y="132" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>{value} A</text><text x="238" y="75" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>2 A</text><text x="248" y="238" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>{value - 2} A</text></>;
  return <><path d="M50 150H125M195 150H270" {...ink}/><path d="M125 95V205M195 95V205" {...red}/><circle cx="125" cy="75" r={5 + value / 2} fill="var(--vs-burgundy)"/><circle cx="195" cy="225" r={5 + value / 2} fill="var(--vs-ink)"/><text x="160" y="265" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>placas com cargas opostas</text></>;
}
function firstSentence(text?: string) { const sentence = text?.split(/(?<=[.!?])\s/)[0] ?? ''; return sentence.length > 180 ? `${sentence.slice(0, 176)}…` : sentence; }
export function electricInstrument(id: ElectricId) { const config = ELECTRIC[id]; return function ElectricBoard(props: BoardProps) { const [value, setValue] = useState(config.control.initial); const readouts = config.readouts(value); const pivot = readouts.find((item) => item.pivot) ?? readouts[0]; const pair = boardPair(props); const first = props.map.nodes[0]; const second = props.map.nodes[2] ?? props.map.nodes.at(-1); return <BoardShell kicker="Laboratório de eletrodinâmica" title={config.name} subtitle={config.question} condition={{ label: 'Leitura', value: pivot.value }} ariaLabel={`Instrumento elétrico: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value}/></svg><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`electric-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{value}</b></label><input id={`electric-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={(event) => setValue(Number(event.target.value))}/></div></div><dl className="vs-plane-readouts">{readouts.map((item) => <div key={item.label} data-pivot={item.pivot ? 'true' : undefined}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></div>} left={{ label: STAGE_LABEL[first?.stage ?? 'conceito'], headline: first?.label ?? props.map.title, detail: firstSentence(first?.excerpt), formula: config.formula }} right={{ label: STAGE_LABEL[second?.stage ?? 'aplicacao'], headline: second?.label ?? props.map.title, detail: firstSentence(second?.excerpt), formula: pivot.value }} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{ label: 'Relação elétrica', general: config.formula, condition: 'mostra', reduced: pivot.value }} closing={config.insight}/>; }; }
