import React, { useState } from 'react';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import { STAGE_LABEL } from '../../lib/visualStudy';
import { ELECTRO, type ElectrostaticsId } from '../../lib/electrostaticsLab';
import type { BoardProps } from '../visual-boards/types';
const ink = { stroke: 'var(--vs-ink)', strokeWidth: 3, fill: 'none' };
const red = { stroke: 'var(--vs-burgundy)', strokeWidth: 4, fill: 'none' };
function Scene({ id, value }: { id: ElectrostaticsId; value: number }) {
  if (id === 'coulomb') return <><circle cx="80" cy="150" r="24" fill="var(--vs-burgundy)"/><circle cx={80 + value * 24} cy="150" r="24" fill="var(--vs-paper)" stroke="var(--vs-ink)" strokeWidth="3"/><text x="80" y="158" textAnchor="middle" fill="white" style={{ fontWeight: 900 }}>+</text><text x={80 + value * 24} y="158" textAnchor="middle" style={{ fontWeight: 900, fill: 'var(--vs-ink)' }}>−</text><path d={`M108 115L${80 + value * 24 - 28} 115`} {...red}/><text x="160" y="260" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>atração a distância r</text></>;
  if (id === 'field') return <><circle cx="160" cy="150" r="24" fill="var(--vs-burgundy)"/><text x="160" y="158" textAnchor="middle" fill="white" style={{ fontWeight: 900 }}>+</text>{[0, 60, 120, 180, 240, 300].map((angle) => { const rad = angle * Math.PI / 180; return <path key={angle} d={`M${160 + 30 * Math.cos(rad)} ${150 + 30 * Math.sin(rad)}L${160 + (70 + value * 8) * Math.cos(rad)} ${150 + (70 + value * 8) * Math.sin(rad)}`} {...red}/>; })}<text x="160" y="280" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>linhas saem de +Q</text></>;
  if (id === 'potential') return <><circle cx="100" cy="150" r="24" fill="var(--vs-burgundy)"/><text x="100" y="158" textAnchor="middle" fill="white" style={{ fontWeight: 900 }}>+</text>{[55, 95, 135].map((r) => <circle key={r} cx="100" cy="150" r={r} {...ink} opacity=".45"/>)}<circle cx={100 + value * 12} cy="150" r="8" fill="var(--vs-ink)"/><text x="160" y="285" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>equipotenciais concêntricas</text></>;
  if (id === 'uniform-field') return <><path d="M85 55V245M235 55V245" {...ink} strokeWidth="8"/><text x="85" y="42" textAnchor="middle" style={{ fontWeight: 900, fill: 'var(--vs-ink)' }}>+</text><text x="235" y="42" textAnchor="middle" style={{ fontWeight: 900, fill: 'var(--vs-ink)' }}>−</text>{[85, 125, 165, 205].map((y) => <path key={y} d="M105 85H215" {...red} transform={`translate(0 ${y - 85})`}/>) }<circle cx={105 + value * 13} cy="150" r="9" fill="var(--vs-burgundy)"/></>;
  return <><path d="M55 150H265" {...red}/><path d="M245 130l20 20-20 20" {...red}/><circle cx={65 + value * 17} cy="150" r="18" fill="var(--vs-burgundy)"/><text x={65 + value * 17} y="158" textAnchor="middle" fill="white" style={{ fontWeight: 900 }}>+</text><text x="160" y="230" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>F = qE</text></>;
}
function short(text?: string) { const sentence = text?.split(/(?<=[.!?])\s/)[0] ?? ''; return sentence.length > 180 ? `${sentence.slice(0, 176)}…` : sentence; }
export function electrostaticsInstrument(id: ElectrostaticsId) { const config = ELECTRO[id]; return function ElectrostaticsBoard(props: BoardProps) { const [value, setValue] = useState(config.control.initial); const readouts = config.readouts(value); const pivot = readouts.find((item) => item.pivot) ?? readouts[0]; const pair = boardPair(props); const first = props.map.nodes[0]; const second = props.map.nodes[2] ?? props.map.nodes.at(-1); return <BoardShell kicker="Laboratório de eletrostática" title={config.name} subtitle={config.question} condition={{ label: 'Leitura', value: pivot.value }} ariaLabel={`Instrumento de eletrostática: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value}/></svg><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`electro-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{value}</b></label><input id={`electro-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={(event) => setValue(Number(event.target.value))}/></div></div><dl className="vs-plane-readouts">{readouts.map((item) => <div key={item.label} data-pivot={item.pivot ? 'true' : undefined}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></div>} left={{ label: STAGE_LABEL[first?.stage ?? 'conceito'], headline: first?.label ?? props.map.title, detail: short(first?.excerpt), formula: config.formula }} right={{ label: STAGE_LABEL[second?.stage ?? 'aplicacao'], headline: second?.label ?? props.map.title, detail: short(second?.excerpt), formula: pivot.value }} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{ label: 'Relação eletrostática', general: config.formula, condition: 'mostra', reduced: pivot.value }} closing={config.insight}/>; }; }
