import React, { useState } from 'react';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import { STAGE_LABEL } from '../../lib/visualStudy';
import { MAGNETISM, type MagnetismId } from '../../lib/magnetismLab';
import type { BoardProps } from '../visual-boards/types';

const ink = { stroke: 'var(--vs-ink)', strokeWidth: 3, fill: 'none' };
const accent = { stroke: 'var(--vs-burgundy)', strokeWidth: 4, fill: 'none' };
function Label({ x, y, children }: { x: number; y: number; children: React.ReactNode }) { return <text x={x} y={y} textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>{children}</text>; }
function Scene({ id, value }: { id: MagnetismId; value: number }) {
  if (id === 'fio-espira') return <><circle cx="160" cy="150" r="16" fill="var(--vs-burgundy)"/><path d="M160 72v156" {...accent}/>{[45, 78, 112].map((r) => <circle key={r} cx="160" cy="150" r={r} {...ink} opacity={Math.max(.25, value / 10)} />)}<Label x={160} y={278}>linhas circulares de B</Label></>;
  if (id === 'carga-em-b') { const y = 205 - value; return <><text x="52" y="62" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>×  ×  ×  B entrando</text><path d="M45 225C125 225 150 225 180 175S250 115 286 115" {...accent}/><circle cx="72" cy="225" r="11" fill="var(--vs-burgundy)"/><path d={`M180 175L220 ${Math.max(82, y)}`} {...ink}/><Label x={160} y={278}>v × B aponta a curvatura</Label></>; }
  if (id === 'fios-paralelos') return <><path d="M105 45V235M215 45V235" {...ink}/><path d="M105 95V185M215 95V185" {...accent}/><path d="M125 145H195M195 145l-14-10m14 10-14 10" {...accent}/><Label x={105} y={72}>I ↑</Label><Label x={215} y={72}>I ↑</Label><Label x={160} y={278}>{value === 0 ? 'sem corrente, sem força' : 'mesmo sentido: atração'}</Label></>;
  if (id === 'lenz') return <><rect x="42" y="100" width="70" height="100" rx="9" fill="var(--vs-burgundy)" opacity=".42"/><Label x={77} y={155}>N</Label><circle cx="210" cy="150" r="62" {...ink}/><path d="M160 150h96m-14-12 14 12-14 12" {...accent}/><path d="M190 90a62 62 0 0 1 64 65" {...accent}/><Label x={210} y={245}>espira reage à mudança</Label></>;
  const angle = value * 9; return <><rect x="54" y="52" width="58" height="194" rx="8" fill="var(--vs-burgundy)" opacity=".35"/><rect x="208" y="52" width="58" height="194" rx="8" fill="var(--vs-ink)" opacity=".22"/><Label x={83} y={78}>N</Label><Label x={237} y={78}>S</Label><g transform={`rotate(${angle} 160 150)`}><rect x="126" y="105" width="68" height="90" {...ink}/><path d="M160 105V195" {...accent}/></g><path d="M113 255a55 28 0 0 0 94 0" {...accent}/><Label x={160} y={282}>rotação → fluxo variável</Label></>;
}
function firstSentence(text?: string) { const sentence = text?.split(/(?<=[.!?])\s/)[0] ?? ''; return sentence.length > 180 ? `${sentence.slice(0, 176)}…` : sentence; }
export function magnetismInstrument(id: MagnetismId) { const config = MAGNETISM[id]; return function MagnetismBoard(props: BoardProps) { const [value, setValue] = useState(config.control.initial); const readouts = config.readouts(value); const pivot = readouts.find((item) => item.pivot) ?? readouts[0]; const pair = boardPair(props); const first = props.map.nodes[0]; const second = props.map.nodes[2] ?? props.map.nodes.at(-1); return <BoardShell kicker="Laboratório de magnetismo" title={config.name} subtitle={config.question} condition={{ label: 'Leitura', value: pivot.value }} ariaLabel={`Instrumento de magnetismo: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value} /></svg><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`magnetism-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{value}</b></label><input id={`magnetism-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={(event) => setValue(Number(event.target.value))} /></div></div><dl className="vs-plane-readouts">{readouts.map((item) => <div key={item.label} data-pivot={item.pivot ? 'true' : undefined}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></div>} left={{ label: STAGE_LABEL[first?.stage ?? 'conceito'], headline: first?.label ?? props.map.title, detail: firstSentence(first?.excerpt), formula: config.formula }} right={{ label: STAGE_LABEL[second?.stage ?? 'aplicacao'], headline: second?.label ?? props.map.title, detail: firstSentence(second?.excerpt), formula: pivot.value }} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{ label: 'Relação magnética', general: config.formula, condition: 'mostra', reduced: pivot.value }} closing={config.insight} />; }; }
