import React, { useState } from 'react';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import { STAGE_LABEL } from '../../lib/visualStudy';
import { MATRIX_CONFIGS, type MatrixConfigId } from '../../lib/matrixLab';
import type { BoardProps } from '../visual-boards/types';
import './MatrixInstrument.css';

function M({children,x,y,accent=false}:{children:React.ReactNode;x:number;y:number;accent?:boolean}){return <text className={accent?'vs-matrix-accent':'vs-matrix-text'} x={x} y={y} textAnchor="middle">{children}</text>}
function Scene({id,value}:{id:MatrixConfigId;value:number}){
 if(id==='sistemas'){const px=60+value*19,py=246-(10-value)*19;return <><path className="vs-matrix-axis" d="M40 246H280M60 270V36"/><path className="vs-matrix-line" d="M60 56L250 246"/><path className="vs-matrix-line vs-matrix-line-b" d="M60 246L250 56"/><circle className="vs-matrix-dot" cx={px} cy={py} r="6"/><M x={160} y={284}>x = {value}; y = {10-value}</M></>}
 if(id==='matrizes'){const a=value;return <><path className="vs-matrix-bracket" d="M50 65H38V185H50M126 65H138V185H126M182 65H170V185H182M258 65H270V185H258M142 125H165"/><M x={78} y={108}>2</M><M x={108} y={108}>3</M><M x={78} y={155}>4</M><M x={108} y={155} accent>{a}</M><M x={208} y={108}>1</M><M x={238} y={108}>−1</M><M x={208} y={155}>0</M><M x={238} y={155}>2</M><M x={160} y={230}>(A + B)₂₂ = {a+2}</M></>}
 if(id==='produto'){const z=value*5+14;return <><path className="vs-matrix-bracket" d="M48 85H36V165H48M112 85H124V165H112M205 85H193V165H205M269 85H281V165H269"/><M x={70} y={118} accent>{value}</M><M x={94} y={118}>2</M><M x={227} y={118}>5</M><M x={251} y={118}>7</M><path className="vs-matrix-dotline" d="M60 132H105M217 132H262"/><M x={160} y={222}>{value} × 5 + 2 × 7 = {z}</M><M x={160} y={258}>linha · coluna</M></>}
 if(id==='determinante'){const d=10-3*value;return <><path className="vs-matrix-area" d={`M70 220L230 220L${70+value*24} 70Z`}/><path className="vs-matrix-axis" d="M44 220H270M70 250V44"/><M x={128} y={108}>[ 2  3 ]</M><M x={128} y={144}>[ {value}  5 ]</M><M x={180} y={268} accent>det = {d}</M></>}
 const k=value; const type=k===1?'secantes':k===2?'coincidentes':'paralelas';return <><path className="vs-matrix-axis" d="M38 244H282M62 268V38"/>{k===1?<><path className="vs-matrix-line" d="M72 224L244 62"/><path className="vs-matrix-line vs-matrix-line-b" d="M72 68L244 224"/></>:k===2?<><path className="vs-matrix-line" d="M72 218L244 68"/><path className="vs-matrix-line vs-matrix-line-b" d="M72 218L244 68"/></>:<><path className="vs-matrix-line" d="M72 210L244 60"/><path className="vs-matrix-line vs-matrix-line-b" d="M72 238L244 88"/></>}<M x={160} y={282}>{type}</M></>}
function short(text?:string){const s=text?.trim().split(/(?<=[.!?])\s/)[0]??'';return s.length>180?`${s.slice(0,176)}…`:s}
const symbols:Record<MatrixConfigId,string>={sistemas:'∩',matrizes:'+',produto:'·',determinante:'det',discussao:'∞'};
export function matrixInstrument(id:MatrixConfigId){const config=MATRIX_CONFIGS[id];return function MatrixBoard(props:BoardProps){const pair=boardPair(props);const [value,setValue]=useState(config.control.initial);const readings=config.readouts(value);const pivot=readings.find(r=>r.pivot)??readings[0];const first=props.map.nodes[0],second=props.map.nodes[2]??props.map.nodes.at(-1);return <BoardShell kicker="Laboratório de matrizes e sistemas" title={config.name} subtitle={config.question} condition={{label:symbols[id],value:pivot.value}} ariaLabel={`Instrumento de matrizes e sistemas: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument vs-matrix-instrument"><svg className="vs-plane vs-matrix" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value}/></svg><p className="vs-instrument-dica">mexa no valor e compare a estrutura com a consequência</p><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`matrix-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{value}</b></label><input id={`matrix-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={e=>setValue(Number(e.target.value))}/></div></div><dl className="vs-plane-readouts">{readings.map(r=><div key={r.label} data-pivot={r.pivot?'true':undefined}><dt>{r.label}</dt><dd>{r.value}</dd></div>)}</dl></div>} left={{label:STAGE_LABEL[first?.stage??'conceito'],headline:first?.label??props.map.title,detail:short(first?.excerpt),formula:config.formula}} right={{label:STAGE_LABEL[second?.stage??'aplicacao'],headline:second?.label??props.map.title,detail:short(second?.excerpt),formula:`${pivot.label} = ${pivot.value}`}} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{label:'Leitura estrutural',general:config.formula,condition:'mostra',reduced:pivot.value}} closing={config.insight}/>}}
