import React,{useState}from'react';import BoardShell from'../visual-boards/BoardShell';import{boardPair}from'../visual-boards/pair';import{STAGE_LABEL}from'../../lib/visualStudy';import{REMAINING,type RemainingId}from'../../lib/remainingMath';import type{BoardProps}from'../visual-boards/types';
function short(t?:string){const s=t?.trim().split(/(?<=[.!?])\s/)[0]??'';return s.length>180?`${s.slice(0,176)}…`:s}const ink={stroke:'var(--vs-ink)',strokeWidth:2,fill:'none'} as const;const red={stroke:'var(--vs-burgundy)',strokeWidth:3,fill:'none'} as const;const tx={fontWeight:800,fill:'var(--vs-ink)'} as const;
function Scene({id,v}:{id:RemainingId;v:number}){if(id==='fila'||id==='grupo')return <>{[0,1,2,3,4,5].map(i=><g key={i}><circle cx={55+i*42} cy={id==='fila'?145:145+(i%2)*42} r="14" fill={i<v?'var(--vs-burgundy)':'var(--vs-paper)'} stroke="var(--vs-ink)"/><text x={55+i*42} y={150} textAnchor="middle" style={tx}>{i+1}</text></g>)}<text x="160" y="255" textAnchor="middle" style={tx}>{id==='fila'?'ordem importa':'ordem não importa'}</text></>;
if(id==='prob'||id==='eventos')return <><circle cx="125" cy="145" r="62" {...red}/><circle cx="195" cy="145" r="62" {...ink}/><text x="104" y="145" style={tx}>A</text><text x="210" y="145" style={tx}>B</text><text x="160" y="148" textAnchor="middle" style={tx}>{v}</text><text x="160" y="255" textAnchor="middle" style={tx}>{id==='prob'?'união e interseção':'relação entre eventos'}</text></>;
if(id==='estatistica')return <>{[2,4,4,5,v].map((n,i)=><rect key={i} x={48+i*45} y={230-n*8} width="28" height={n*8} fill="var(--vs-burgundy)" opacity={i===4 ? .9 : .45}/>)}<path d="M40 232H280" {...ink}/><text x="160" y="270" textAnchor="middle" style={tx}>amostra ordenada</text></>;
if(id==='trig-poligonos'||id==='trig-outras')return <><path d="M55 225L260 225L160 65Z" {...red}/><path d="M160 225L160 65" {...ink}/><text x="160" y="248" textAnchor="middle" style={tx}>{id==='trig-poligonos'?'lado / sen(ângulo) = 2R':`θ = ${v}°`}</text></>;
if(id==='espaco')return <><path d="M65 205L205 115M115 235L255 145" {...red}/><path d="M65 110L205 200" {...ink}/><text x="160" y="270" textAnchor="middle" style={tx}>{['','paralelas','concorrentes','reversas'][v]}</text></>;
if(id==='conicas')return <><path d="M80 230L160 60L240 230M80 90L240 90" {...red}/><path d={v===1?'M55 150H265':v===2?'M95 90L225 230':'M65 120L255 120'} {...ink}/><text x="160" y="270" textAnchor="middle" style={tx}>{['','hipérbole','parábola','elipse'][v]}</text></>;
if(id==='composicao')return <><rect x="42" y="112" width="62" height="52" rx="9" {...ink}/><rect x="129" y="112" width="62" height="52" rx="9" {...red}/><rect x="216" y="112" width="62" height="52" rx="9" {...ink}/><text x="73" y="143" textAnchor="middle" style={tx}>{v}</text><text x="160" y="143" textAnchor="middle" style={tx}>g</text><text x="247" y="143" textAnchor="middle" style={tx}>f</text><text x="160" y="235" textAnchor="middle" style={tx}>x → g(x) → f(g(x))</text></>;
return <>{[0,1,2,3].map(i=><g key={i}><circle cx="75" cy={75+i*45} r="10" fill="var(--vs-paper)" stroke="var(--vs-ink)"/><circle cx="245" cy={75+i*45} r="10" fill="var(--vs-paper)" stroke="var(--vs-burgundy)"/><path d={`M85 ${75+i*45}H235`} {...red}/></g>)}<text x="160" y="275" textAnchor="middle" style={tx}>{v===4?'um para um e sobre':'imagem repetida ou ausente'}</text></>}
export function remainingMathInstrument(id:RemainingId){const c=REMAINING[id];return function RBoard(props:BoardProps){const p=boardPair(props);const[v,setV]=useState(c.control.initial),r=c.readouts(v),pivot=r.find(x=>x.pivot)??r[0],a=props.map.nodes[0],b=props.map.nodes[2]??props.map.nodes.at(-1);return <BoardShell kicker="Laboratório de matemática" title={c.name} subtitle={c.question} condition={{label:'→',value:pivot.value}} ariaLabel={`Instrumento de matemática: ${props.map.title}`} emphasis={p.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${c.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} v={v}/></svg><p className="vs-instrument-dica">mexa no caso e compare a regra com sua consequência</p><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`rm-${id}`}><strong>{c.control.label}</strong><span>{c.control.description}</span><b>{v}</b></label><input id={`rm-${id}`} type="range" min={c.control.min} max={c.control.max} step={c.control.step} value={v} onChange={e=>setV(Number(e.target.value))}/></div></div><dl className="vs-plane-readouts">{r.map(x=><div key={x.label} data-pivot={x.pivot?'true':undefined}><dt>{x.label}</dt><dd>{x.value}</dd></div>)}</dl></div>} left={{label:STAGE_LABEL[a?.stage??'conceito'],headline:a?.label??props.map.title,detail:short(a?.excerpt),formula:c.formula}} right={{label:STAGE_LABEL[b?.stage??'aplicacao'],headline:b?.label??props.map.title,detail:short(b?.excerpt),formula:`${pivot.label} = ${pivot.value}`}} leftState={p.leftState} rightState={p.rightState} leftSelected={p.leftSelected} rightSelected={p.rightSelected} onSelectLeft={p.selectLeft} onSelectRight={p.selectRight} equation={{label:'Leitura matemática',general:c.formula,condition:'mostra',reduced:pivot.value}} closing={c.insight}/>}}
