import React,{useState}from'react';
import BoardShell from '../visual-boards/BoardShell';
import {boardPair} from '../visual-boards/pair';
import {STAGE_LABEL} from '../../lib/visualStudy';
import {THERMO,type ThermoId} from '../../lib/thermoLab';
import type {BoardProps} from '../visual-boards/types';
function short(text?:string){const s=text?.trim().split(/(?<=[.!?])\s/)[0]??'';return s.length>180?`${s.slice(0,176)}…`:s}
function Scene({id,v}:{id:ThermoId;v:number}){if(id==='gas-work')return <><path d="M45 235H280M65 255V45" stroke="var(--vs-ink)" strokeWidth="2"/><path d={`M90 190H${90+v*18}V110H90Z`} fill="color-mix(in srgb,var(--vs-burgundy) 28%,transparent)" stroke="var(--vs-burgundy)" strokeWidth="3"/><text x="164" y="278" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>área = trabalho</text></>;
if(id==='first-law')return <><circle cx="160" cy="150" r="58" fill="var(--vs-paper)" stroke="var(--vs-ink)" strokeWidth="3"/><path d="M45 150H100M220 150H275" stroke="var(--vs-burgundy)" strokeWidth="8"/><text x="72" y="130" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>Q</text><text x="248" y="130" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>W</text><text x="160" y="156" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>ΔU={12-v}</text></>;
return <><rect x="105" y="45" width="110" height="44" rx="10" fill="var(--vs-burgundy)" opacity=".45"/><rect x="105" y="210" width="110" height="44" rx="10" fill="var(--vs-ink)" opacity=".25"/><path d="M160 90V208M215 150H270" stroke="var(--vs-burgundy)" strokeWidth="5"/><text x="160" y="73" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>fonte quente</text><text x="160" y="240" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>fonte fria</text><text x="250" y="140" textAnchor="middle" style={{fontWeight:800,fill:'var(--vs-ink)'}}>W</text></>}
export function thermoInstrument(id:ThermoId){const config=THERMO[id];return function ThermoBoard(props:BoardProps){const pair=boardPair(props);const [v,setV]=useState(config.control.initial),readouts=config.readouts(v),pivot=readouts.find(x=>x.pivot)??readouts[0],first=props.map.nodes[0],second=props.map.nodes[2]??props.map.nodes.at(-1);return <BoardShell kicker="Laboratório de termodinâmica" title={config.name} subtitle={config.question} condition={{label:'Δ',value:pivot.value}} ariaLabel={`Instrumento de termodinâmica: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} v={v}/></svg><p className="vs-instrument-dica">mexa na variável e acompanhe o balanço de energia</p><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`thermo-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{v}</b></label><input id={`thermo-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={v} onChange={e=>setV(Number(e.target.value))}/></div></div><dl className="vs-plane-readouts">{readouts.map(x=><div key={x.label} data-pivot={x.pivot?'true':undefined}><dt>{x.label}</dt><dd>{x.value}</dd></div>)}</dl></div>} left={{label:STAGE_LABEL[first?.stage??'conceito'],headline:first?.label??props.map.title,detail:short(first?.excerpt),formula:config.formula}} right={{label:STAGE_LABEL[second?.stage??'aplicacao'],headline:second?.label??props.map.title,detail:short(second?.excerpt),formula:pivot.value}} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{label:'Balanço térmico',general:config.formula,condition:'mostra',reduced:pivot.value}} closing={config.insight}/>}}
