import React, { useState } from 'react';
import BoardShell from '../visual-boards/BoardShell';
import { boardPair } from '../visual-boards/pair';
import { STAGE_LABEL } from '../../lib/visualStudy';
import { WAVES, type WavesId } from '../../lib/wavesLab';
import type { BoardProps } from '../visual-boards/types';

const ink = { stroke: 'var(--vs-ink)', strokeWidth: 3, fill: 'none' };
const wine = { stroke: 'var(--vs-burgundy)', strokeWidth: 4, fill: 'none' };
const short = (text?: string) => { const sentence = text?.trim().split(/(?<=[.!?])\s/)[0] ?? ''; return sentence.length > 180 ? `${sentence.slice(0, 176)}…` : sentence; };
const wave = (amplitude: number, phase = 0) => Array.from({ length: 17 }, (_, i) => `${i ? 'L' : 'M'} ${35 + i * 16} ${150 - amplitude * Math.sin((i / 16) * Math.PI * 4 + phase)}`).join(' ');

function Scene({ id, value }: { id: WavesId; value: number }) {
  if (id === 'wave-equation') { const spacing = 200 / value; return <><path d={wave(32)} {...wine}/>{Array.from({ length: Math.max(1, Math.floor(value / 2)) }, (_, i) => <path key={i} d={`M${50 + i * spacing} 225h${spacing}`} {...ink}/>) }<text x="160" y="260" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>mais f → menor λ</text></>; }
  if (id === 'sound-intensity') return <><circle cx="85" cy="150" r="14" fill="var(--vs-burgundy)"/><circle cx="85" cy="150" r={30 + value * 12} {...ink}/><circle cx="85" cy="150" r={15 + value * 6} {...wine}/><path d={`M85 150H${85 + 30 + value * 12}`} {...wine}/><circle cx={85 + 30 + value * 12} cy="150" r="7" fill="var(--vs-ink)"/><text x="160" y="270" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>a área cresce como r²</text></>;
  if (id === 'interference') { const phase = value * Math.PI / 180; return <><path d={wave(21)} stroke="var(--vs-ink)" strokeWidth="2" fill="none" opacity=".55"/><path d={wave(21, phase)} stroke="var(--vs-burgundy)" strokeWidth="2" fill="none" opacity=".55"/><path d={wave(42 * Math.abs(Math.cos(phase / 2)), phase / 2)} stroke="var(--vs-burgundy)" strokeWidth="5" fill="none"/><text x="160" y="268" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>resultado da superposição</text></>; }
  if (id === 'string-harmonics') { const nodes = Array.from({ length: value + 1 }, (_, i) => 35 + (250 * i) / value); const path = Array.from({ length: 81 }, (_, i) => { const x = 35 + i * 3.125; return `${i ? 'L' : 'M'} ${x} ${150 - 55 * Math.sin((i / 80) * Math.PI * value)}`; }).join(' '); return <><path d="M35 150H285" {...ink}/><path d={path} {...wine}/>{nodes.map(x => <circle key={x} cx={x} cy="150" r="6" fill="var(--vs-ink)"/>)}<text x="160" y="270" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>{value} ventre{value > 1 ? 's' : ''}; nós fixos</text></>; }
  const gap = 30 - value / 4; return <><circle cx="120" cy="150" r="17" fill="var(--vs-burgundy)"/><path d="M125 150h30" {...wine}/><path d="M108 118l-50-35M108 140l-68-12M108 162l-68 12M108 184l-50 35" {...ink}/><path d={`M132 118l${gap} -35M132 140l${gap + 18} -12M132 162l${gap + 18} 12M132 184l${gap} 35`} {...wine}/><circle cx="270" cy="150" r="8" fill="var(--vs-ink)"/><text x="160" y="270" textAnchor="middle" style={{ fontWeight: 800, fill: 'var(--vs-ink)' }}>frentes comprimidas à frente</text></>;
}

export function wavesInstrument(id: WavesId) {
  const config = WAVES[id];
  return function WavesBoard(props: BoardProps) {
    const [value, setValue] = useState(config.control.initial); const readouts = config.readouts(value); const pivot = readouts.find(item => item.pivot) ?? readouts[0]; const pair = boardPair(props); const first = props.map.nodes[0]; const second = props.map.nodes[2] ?? props.map.nodes.at(-1);
    return <BoardShell kicker="Laboratório de ondulatória" title={config.name} subtitle={config.question} condition={{ label: 'Leitura', value: pivot.value }} ariaLabel={`Instrumento de ondulatória: ${props.map.title}`} emphasis={pair.emphasis} scene={<div className="vs-instrument"><svg className="vs-plane" viewBox="0 0 320 300" role="img" aria-label={`${config.name}; ${pivot.label}: ${pivot.value}`}><Scene id={id} value={value}/></svg><p className="vs-instrument-dica">mexa na grandeza e relacione a forma da onda à leitura</p><div className="vs-plane-controls"><div className="vs-plane-control"><label htmlFor={`waves-${id}`}><strong>{config.control.label}</strong><span>{config.control.description}</span><b>{value}</b></label><input id={`waves-${id}`} type="range" min={config.control.min} max={config.control.max} step={config.control.step} value={value} onChange={event => setValue(Number(event.target.value))}/></div></div><dl className="vs-plane-readouts">{readouts.map(item => <div key={item.label} data-pivot={item.pivot ? 'true' : undefined}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></div>} left={{ label: STAGE_LABEL[first?.stage ?? 'conceito'], headline: first?.label ?? props.map.title, detail: short(first?.excerpt), formula: config.formula }} right={{ label: STAGE_LABEL[second?.stage ?? 'aplicacao'], headline: second?.label ?? props.map.title, detail: short(second?.excerpt), formula: pivot.value }} leftState={pair.leftState} rightState={pair.rightState} leftSelected={pair.leftSelected} rightSelected={pair.rightSelected} onSelectLeft={pair.selectLeft} onSelectRight={pair.selectRight} equation={{ label: 'Relação ondulatória', general: config.formula, condition: 'mostra', reduced: pivot.value }} closing={config.insight}/>;
  };
}
