import type { QualityReview } from './visualQuality';

/** Registro explícito da relação visual; aprovação exige evidência em navegador. */
const ecologyEvidence = (chapterId: string) =>
  ['390', '1440'].flatMap(viewport =>
    ['light', 'dark'].map(theme =>
      `docs/visual-personalizado/screenshots/ecologia-motion-2026-09-23/${chapterId}-${viewport}-${theme}.png`,
    ),
  );

const qaNotes = 'Reaberto após rejeição visual da responsável em 2026-09-23. Cenas refeitas com movimento no mecanismo; aprovação editorial pendente. Evidências novas: 60 verificações de largura/seleção e capturas em 390 e 1440 px nos dois temas.';

const mechanismExpansion: Array<[string, string, string]> = [
  ['summary-fisica-equacao-fundamental-da-ondulatoria', 'corda com ponto material destacado', 'perfil se propaga enquanto um ponto oscila; v = λf'],
  ['summary-fisica-ondulatoria-ondas-eletromagneticas', 'campos E e B em perspectiva', 'campos transversais em fase, com amplitudes normalizadas'],
  ['summary-fisica-ondulatoria-som-e-suas-propriedades', 'partículas em compressões e rarefações', 'oscilação longitudinal do meio sem transporte líquido de matéria'],
  ['summary-quimica-termoquimica-i', 'perfil de entalpia e fluxo sistema-vizinhança', 'saldo ΔH e barreira Ea distintos; troca de calor muda de sentido'],
  ['summary-quimica-termoquimica-ii', 'caminhos direto e por intermediário', 'mesmos estados extremos dão o mesmo ΔH; intermediários se cancelam'],
  ['summary-quimica-evolucao-dos-modelos-atomicos', 'espalhamento alfa e níveis discretos do hidrogênio', 'grandes desvios sustentam núcleo concentrado; fóton corresponde à diferença de energia'],
  ['summary-biologia-coracao-e-vasos-sanguineos', 'percurso selecionável entre cavidades, pulmões e corpo', 'artéria e veia definidas pela direção, não pela oxigenação'],
];

// Rodadas de 25/09 (régua aprovada pela responsável): três recortes a 1440 px
// e a prancha a 390 e 768 px, cada um nos dois temas.
const roundEvidence = (folder: string, chapterId: string, recortes = 3) => {
  const stem = `docs/visual-personalizado/screenshots/${folder}/${chapterId.replace('summary-', '')}`;
  return [
    ...Array.from({ length: recortes }, (_, k) => k + 1).flatMap(n => [`${stem}-recorte${n}.png`, `${stem}-recorte${n}-dark.png`]),
    ...[390, 768].flatMap(w => [`${stem}-${w}-light.png`, `${stem}-${w}-dark.png`]),
  ];
};
const lote1 = (chapterId: string) => roundEvidence('lote1-hg-2026-09-25', chapterId);
const lote2 = (chapterId: string) => roundEvidence('lote2-hg-2026-09-25', chapterId);
const lote3 = (chapterId: string) => roundEvidence('lote3-hg-2026-09-25', chapterId);
const lote4 = (chapterId: string) => roundEvidence('lote4-hg-2026-09-26', chapterId);
// Lotes 5 a 10 guardam captura de todos os recortes, não só dos três primeiros.
const loteN = (lote: string, chapterId: string, recortes: number) => roundEvidence(`lote${lote}-hg-2026-09-26`, chapterId, recortes);
const roundNotes = 'Redesenhada em 25/09 pela régua aprovada: cena própria com movimento que explica o mecanismo. QA técnico: 390, 768 e 1440 px, temas claro e escuro, todos os recortes sem colisão de texto. Aprovação editorial pendente.';
const notes26 = roundNotes.replace('25/09', '26/09');

export const visualQualityReviews: QualityReview[] = [
  ...mechanismExpansion.map(([chapterId, mechanism, relation]): QualityReview => ({
    chapterId, mechanism, relation, status: 'em-validacao',
    evidencePaths: ['390', '1440'].flatMap(width => ['light', 'dark'].map(theme =>
      `docs/visual-personalizado/screenshots/mecanismos-expansao-2026-09-25/${chapterId}-${width}-${theme}.png`)),
    notes: 'QA em 360, 390, 768 e 1440 px nos dois temas: sem overflow horizontal. Capturas de página e controles conferidos. Movimento reduzido coberto por teste de componente, sem emulação no navegador. Aprovação editorial pendente; não equivale a finalização do capítulo.',
  })),
  { chapterId: 'summary-biologia-bioenergetica-fotossintese-e-quimiossintese', mechanism: 'cloroplasto em corte e procarionte quimioautotrófico', relation: 'luz ou oxidação inorgânica fornecem energia; CO₂ fornece carbono', status: 'em-validacao', evidencePaths: ['fotossintese-390-light', 'fotossintese-1440-light', 'quimiossintese-390-dark', 'quimiossintese-1440-dark'].map(name => `docs/visual-personalizado/screenshots/bioenergetica-motion-2026-09-23/${name}.png`), notes: 'Reconstrução com fluxos finitos, seleção por teclado e dez verificações de largura nos dois temas. Movimento reduzido coberto por teste de componente, sem emulação no navegador. Aprovação editorial pendente.' },
  { chapterId: 'bio-ecologia-ciclo-nitrogenio', mechanism: 'ciclo microbiano no solo e atmosfera', relation: 'fixação e amonificação alimentam nitrificação; desnitrificação devolve N₂', status: 'em-validacao', evidencePaths: ecologyEvidence('bio-ecologia-ciclo-nitrogenio'), notes: qaNotes },
  { chapterId: 'bio-ecologia-eutrofizacao', mechanism: 'seção vertical de lago', relation: 'nutrientes induzem floração, bloqueiam luz e levam ao consumo de oxigênio', status: 'em-validacao', evidencePaths: ecologyEvidence('bio-ecologia-eutrofizacao'), notes: qaNotes },
  { chapterId: 'bio-ecologia-dinamica-populacoes', mechanism: 'perfis reprodutivos', relation: 'muitos descendentes e pouco cuidado versus poucos descendentes e longo cuidado', status: 'em-validacao', evidencePaths: ecologyEvidence('bio-ecologia-dinamica-populacoes'), notes: qaNotes },
  { chapterId: 'bio-ecologia-invasoras-controle-biologico', mechanism: 'rede de impactos', relation: 'invasora alcança nativas, recursos, genes e ambiente por cinco caminhos', status: 'em-validacao', evidencePaths: ecologyEvidence('bio-ecologia-invasoras-controle-biologico'), notes: qaNotes },
  { chapterId: 'bio-ecologia-sucessao', mechanism: 'paisagem de comunidades', relation: 'solo e vegetação mudam da pioneira ao clímax', status: 'em-validacao', evidencePaths: ecologyEvidence('bio-ecologia-sucessao'), notes: qaNotes },
  { chapterId: 'bio-ecologia-ciclo-hidrologico-poluicao-agua', mechanism: 'fonte, água e efeito', relation: 'cada agente altera o meio aquático por consequência própria', status: 'em-validacao', evidencePaths: ecologyEvidence('bio-ecologia-ciclo-hidrologico-poluicao-agua'), notes: qaNotes },
  { chapterId: 'summary-historia-revolucao-francesa', mechanism: 'cronologia com forças políticas e militares', relation: 'crise fiscal abre conflito institucional; guerra externa e desconfiança interna compõem a radicalização', status: 'em-validacao', evidencePaths: lote1('summary-historia-revolucao-francesa'), notes: roundNotes },
  { chapterId: 'summary-historia-revolucao-industrial', mechanism: 'campo cercado, fábrica e documento legal', relation: 'cercamentos liberam mão de obra e capital; documentação e pressão social contribuem para reformas', status: 'em-validacao', evidencePaths: lote1('summary-historia-revolucao-industrial'), notes: roundNotes },
  { chapterId: 'summary-geografia-projecoes-cartograficas', mechanism: 'comparação esquemática de três propriedades cartográficas', relation: 'conforme preserva forma local; equivalente, área; equidistante, distâncias desde um centro', status: 'em-validacao', evidencePaths: lote1('summary-geografia-projecoes-cartograficas'), notes: roundNotes },
  { chapterId: 'summary-geografia-dinamica-climatica', mechanism: 'seções de ascensão do ar', relation: 'aquecimento, barreira montanhosa e encontro de massas criam chuvas por mecanismos distintos', status: 'em-validacao', evidencePaths: lote1('summary-geografia-dinamica-climatica'), notes: roundNotes },
  { chapterId: 'summary-geografia-energia-eletrica-no-brasil', mechanism: 'usina, rede e centro consumidor', relation: 'geração e transmissão conectam fontes a uma demanda variável', status: 'em-validacao', evidencePaths: lote1('summary-geografia-energia-eletrica-no-brasil'), notes: roundNotes },
  { chapterId: 'summary-geografia-estrutura-etnica-e-fluxos-migratorios', mechanism: 'origem, trajeto e destino ligados por redes', relation: 'o deslocamento reorganiza destinos e pode preservar vínculos com a origem', status: 'em-validacao', evidencePaths: lote1('summary-geografia-estrutura-etnica-e-fluxos-migratorios'), notes: roundNotes },
  { chapterId: 'summary-geografia-os-fluxos-do-comercio-externo', mechanism: 'produção, porto e mercado externo', relation: 'a logística e seus custos ligam especialização produtiva a parceiros externos', status: 'em-validacao', evidencePaths: lote1('summary-geografia-os-fluxos-do-comercio-externo'), notes: roundNotes },
  { chapterId: 'summary-geografia-combustiveis-fosseis-e-biocombustiveis-no-brasil', mechanism: 'estoque fóssil, planta e etapa de uso', relation: 'carbono recente não torna biocombustível automaticamente neutro; solo e transporte integram o balanço', status: 'em-validacao', evidencePaths: lote1('summary-geografia-combustiveis-fosseis-e-biocombustiveis-no-brasil'), notes: roundNotes },
  { chapterId: 'summary-historia-a-mineracao-no-brasil-colonial', mechanism: 'casa de fundição, barras e cota anual', relation: 'o quinto separa 20%; a fundição sela o restante e torna ilegal o pó; a derrama cobra de todos a diferença até a cota', status: 'em-validacao', evidencePaths: lote2('summary-historia-a-mineracao-no-brasil-colonial'), notes: roundNotes },
  { chapterId: 'summary-historia-a-interiorizacao-da-colonizacao', mechanism: 'contorno do Brasil com três vetores', relation: 'bandeiras saem de São Paulo, o ouro puxa gente e a capital para o Rio, o gado sobe o São Francisco', status: 'em-validacao', evidencePaths: lote2('summary-historia-a-interiorizacao-da-colonizacao'), notes: roundNotes },
  { chapterId: 'summary-historia-grandes-navegacoes-e-conquista-colonial', mechanism: 'rota do Cabo e litoral do pau-brasil', relation: 'tecnologia náutica leva à Índia; a prioridade asiática deixa o Brasil no escambo até as ameaças de 1530', status: 'em-validacao', evidencePaths: lote2('summary-historia-grandes-navegacoes-e-conquista-colonial'), notes: roundNotes },
  { chapterId: 'summary-historia-a-montagem-da-colonizacao', mechanism: 'balança de fatores (metáfora declarada)', relation: 'resistência, epidemias e oposição jesuíta só juntas explicam a passagem ao tráfico transatlântico', status: 'em-validacao', evidencePaths: lote2('summary-historia-a-montagem-da-colonizacao'), notes: roundNotes },
  { chapterId: 'summary-historia-a-crise-do-antigo-sistema-colonial', mechanism: 'duas revoltas e a corrente do pacto colonial', relation: 'Inconfidência e Conjuração Baiana diferem em composição e pauta, contra o mesmo pacto', status: 'em-validacao', evidencePaths: lote2('summary-historia-a-crise-do-antigo-sistema-colonial'), notes: roundNotes },
  { chapterId: 'summary-historia-dinamica-interna-da-colonizacao', mechanism: 'engenho com casa-grande, senzala, quilombo e roças', relation: 'hierarquia, resistência e atividades subsidiárias convivem na mesma sociedade açucareira', status: 'em-validacao', evidencePaths: lote2('summary-historia-dinamica-interna-da-colonizacao'), notes: roundNotes },
  { chapterId: 'summary-geografia-movimentos-da-terra', mechanism: 'órbita com eixo de inclinação constante', relation: 'o eixo de 23,5° mantém a direção; a incidência dos raios, não a distância, alterna as estações', status: 'em-validacao', evidencePaths: lote3('summary-geografia-movimentos-da-terra'), notes: roundNotes },
  { chapterId: 'summary-geografia-relevo-brasileiro', mechanism: 'perfil com planaltos, depressão e planície', relation: 'planaltos antigos erodidos, planícies de sedimentos recentes, depressões rebaixadas entre planaltos', status: 'em-validacao', evidencePaths: lote3('summary-geografia-relevo-brasileiro'), notes: roundNotes },
  { chapterId: 'summary-geografia-pedologia', mechanism: 'três perfis de solo', relation: 'latossolo profundo e lixiviado, terra roxa sobre basalto, solo raso do semiárido sujeito a sal', status: 'em-validacao', evidencePaths: lote3('summary-geografia-pedologia'), notes: roundNotes },
  { chapterId: 'summary-geografia-climatologia-do-brasil', mechanism: 'mapa de climas com painel por recorte', relation: 'latitude e massas de ar dão equatorial, tropical, semiárido e subtropical', status: 'em-validacao', evidencePaths: lote3('summary-geografia-climatologia-do-brasil'), notes: roundNotes },
  { chapterId: 'summary-geografia-dominios-morfoclimaticos', mechanism: 'mapa dos seis domínios com paisagem', relation: 'clima, relevo, solo e vegetação combinados em domínios com faixas de transição', status: 'em-validacao', evidencePaths: lote3('summary-geografia-dominios-morfoclimaticos'), notes: roundNotes },
  { chapterId: 'summary-geografia-geologia-e-geomorfologia', mechanism: 'corte com vulcão, bacia e rochas profundas', relation: 'magma esfria em ígneas, sedimentos compactam em sedimentares, calor e pressão fazem metamórficas', status: 'em-validacao', evidencePaths: lote3('summary-geografia-geologia-e-geomorfologia'), notes: roundNotes },
  { chapterId: 'summary-historia-brasil-imperio-formacao-do-estado-nacional-brasileiro', mechanism: 'Poder Moderador acima dos três poderes e barra de insatisfação', relation: 'a repressão de 1824 cala a revolta, mas a concentração de poder segue e acumula pressão até a abdicação de 1831', status: 'em-validacao', evidencePaths: lote4('summary-historia-brasil-imperio-formacao-do-estado-nacional-brasileiro'), notes: roundNotes.replace('25/09', '26/09') },
  { chapterId: 'summary-historia-brasil-imperio-o-periodo-regencial-1831-1840', mechanism: 'mapa das revoltas e linha do tempo 1831–1845', relation: 'sem monarca adulto, revoltas regionais se sobrepõem; a Farroupilha dura além da Regência', status: 'em-validacao', evidencePaths: lote4('summary-historia-brasil-imperio-o-periodo-regencial-1831-1840'), notes: roundNotes.replace('25/09', '26/09') },
  { chapterId: 'summary-historia-brasil-imperio-o-declinio-do-segundo-reinado', mechanism: 'plataforma da monarquia sobre três apoios', relation: 'um apoio a menos faz balançar; clero, Exército e cafeicultores juntos derrubam o regime em 1889', status: 'em-validacao', evidencePaths: lote4('summary-historia-brasil-imperio-o-declinio-do-segundo-reinado'), notes: roundNotes.replace('25/09', '26/09') },
  { chapterId: 'summary-historia-ascensao-e-dominio-das-oligarquias', mechanism: 'pirâmide do eleitor dependente ao presidente', relation: 'dependência vira voto de cabresto; apoio federal e votos no Congresso ligam governadores e presidente; SP e MG se revezam', status: 'em-validacao', evidencePaths: lote4('summary-historia-ascensao-e-dominio-das-oligarquias'), notes: roundNotes.replace('25/09', '26/09') },
  { chapterId: 'summary-historia-a-primeira-republica-o-declinio-oligarquico-1889-1930', mechanism: 'elite cafeeira no pedestal e três contestações', relation: 'tenentismo, movimento operário e modernismo contestam a mesma ordem oligárquica em esferas diferentes', status: 'em-validacao', evidencePaths: lote4('summary-historia-a-primeira-republica-o-declinio-oligarquico-1889-1930'), notes: roundNotes.replace('25/09', '26/09') },
  { chapterId: 'summary-geografia-dinamica-demografica', mechanism: 'Duas taxas que se descolam e a pirâmide que muda', relation: 'A mortalidade cai antes da natalidade; a faixa entre as curvas é o crescimento vegetativo e redesenha a pirâmide etária', status: 'em-validacao', evidencePaths: loteN('5', 'summary-geografia-dinamica-demografica', 4), notes: notes26 },
  { chapterId: 'geo-bonus-demografico', mechanism: 'A mão de obra migra do primário ao terciário', relation: 'Países pobres concentram trabalho no primário, os industrializados no secundário, e as economias maduras terciarizam', status: 'em-validacao', evidencePaths: loteN('5', 'geo-bonus-demografico', 3), notes: notes26 },
  { chapterId: 'summary-geografia-o-espaco-urbano-i', mechanism: 'Cada cidade serve às de baixo na rede urbana', relation: 'O nível na hierarquia vem do alcance da influência: do centro local à metrópole nacional ligada à economia global', status: 'em-validacao', evidencePaths: loteN('5', 'summary-geografia-o-espaco-urbano-i', 4), notes: notes26 },
  { chapterId: 'summary-geografia-o-espaco-urbano-ii', mechanism: 'A desigualdade distribuída no espaço da cidade', relation: 'A renda define o lugar; o lugar define o acesso a infraestrutura, emprego, escola e segurança', status: 'em-validacao', evidencePaths: loteN('5', 'summary-geografia-o-espaco-urbano-ii', 3), notes: notes26 },
  { chapterId: 'summary-geografia-mobilidade-populacional', mechanism: 'A origem empurra, o destino puxa', relation: 'A decisão de migrar costuma combinar várias pressões de expulsão com várias atrações ao mesmo tempo', status: 'em-validacao', evidencePaths: loteN('5', 'summary-geografia-mobilidade-populacional', 3), notes: notes26 },
  { chapterId: 'summary-geografia-as-redes-de-transportes', mechanism: 'Cada modal rende numa distância e numa carga', relation: 'Rodovia é porta a porta em curta distância; trem e barcaça levam volume longe; o avião leva carga de alto valor', status: 'em-validacao', evidencePaths: loteN('5', 'summary-geografia-as-redes-de-transportes', 3), notes: notes26 },
  { chapterId: 'summary-historia-a-era-vargas', mechanism: 'Pressão armada leva governo sem mandato à Constituição', relation: 'A Revolução de 1930 põe Vargas no poder sem voto; a revolta paulista de 1932 exige Constituinte e força a Constituição de 1934', status: 'em-validacao', evidencePaths: loteN('6', 'summary-historia-a-era-vargas', 4), notes: notes26 },
  { chapterId: 'summary-historia-a-era-vargas-o-governo-constitucional-1934-1937', mechanism: 'Cada crise vira pretexto para a seguinte, até o golpe', relation: 'AIB × ANL gera instabilidade; a Intentona de 1935 justifica o estado de sítio; o Plano Cohen forjado justifica o golpe de 10/11/1937', status: 'em-validacao', evidencePaths: loteN('6', 'summary-historia-a-era-vargas-o-governo-constitucional-1934-1937', 4), notes: notes26 },
  { chapterId: 'summary-historia-a-era-vargas-o-estado-novo', mechanism: 'Ditadura dentro, guerra ao fascismo fora: contradição', relation: 'Combater o fascismo na Itália com regime semelhante em casa gera pressão por redemocratização; as Forças Armadas depõem Vargas em 1945', status: 'em-validacao', evidencePaths: loteN('6', 'summary-historia-a-era-vargas-o-estado-novo', 3), notes: notes26 },
  { chapterId: 'summary-historia-o-brasil-atual', mechanism: 'Três condições juntas reduzem a desigualdade', relation: 'Bolsa Família, salário mínimo acima da inflação e commodities em alta: só combinados explicam a queda da desigualdade nos anos 2000', status: 'em-validacao', evidencePaths: loteN('6', 'summary-historia-o-brasil-atual', 4), notes: notes26 },
  { chapterId: 'summary-historia-a-historia-e-o-brasil', mechanism: 'Quem narra muda o que se vê no encontro de 1500', relation: 'A historiografia antiga narra do navio; a recente, da aldeia (agência indígena); o debate é sobre autoridade para narrar', status: 'em-validacao', evidencePaths: loteN('6', 'summary-historia-a-historia-e-o-brasil', 3), notes: notes26 },
  { chapterId: 'summary-historia-antiguidade-classica-o-mundo-grego', mechanism: 'Relevo divide póleis; cultura comum as une', relation: 'Póleis autônomas (governo, leis, moeda, exército) separadas pelo relevo, unidas por língua, deuses e Jogos Olímpicos', status: 'em-validacao', evidencePaths: loteN('7a', 'summary-historia-antiguidade-classica-o-mundo-grego', 3), notes: notes26 },
  { chapterId: 'summary-historia-antiguidade-classica-o-mundo-romano', mechanism: 'Poder repartido se concentra em Augusto', relation: 'Senado, assembleias e cônsules repartem o poder; guerras civis o arrancam; Augusto o concentra e mantém as instituições como fachada', status: 'em-validacao', evidencePaths: loteN('7a', 'summary-historia-antiguidade-classica-o-mundo-romano', 3), notes: notes26 },
  { chapterId: 'summary-historia-alta-idade-media-e-feudalismo', mechanism: 'Senhor-servo e nobre-nobre: vínculos distintos', relation: 'O servo deve trabalho, colheita e taxas ao senhor; o vassalo recebe feudo e deve serviço militar e conselho ao suserano', status: 'em-validacao', evidencePaths: loteN('7a', 'summary-historia-alta-idade-media-e-feudalismo', 3), notes: notes26 },
  { chapterId: 'summary-historia-baixa-idade-media', mechanism: 'Peste reduz braços e inverte a barganha', relation: 'A Peste Negra mata de 1/3 a 1/2 da população; a escassez de mão de obra eleva a barganha camponesa e abala o trabalho servil', status: 'em-validacao', evidencePaths: loteN('7a', 'summary-historia-baixa-idade-media', 3), notes: notes26 },
  { chapterId: 'summary-historia-vida-urbana-e-renascimento-cultural', mechanism: 'Riqueza vira mecenato, humanismo e arte', relation: 'Comércio e bancos italianos financiam mecenas (Médici), que sustentam o humanismo antropocêntrico e a arte da perspectiva e da anatomia', status: 'em-validacao', evidencePaths: loteN('7a', 'summary-historia-vida-urbana-e-renascimento-cultural', 4), notes: notes26 },
  { chapterId: 'summary-historia-a-primeira-globalizacao', mechanism: 'Metal como riqueza puxa pacto, trabalho forçado e tráfico', relation: 'A doutrina do metal acumulado cria o pacto colonial exclusivo, que exige trabalho compulsório em larga escala e, por fim, o tráfico atlântico', status: 'em-validacao', evidencePaths: loteN('7b', 'summary-historia-a-primeira-globalizacao', 4), notes: notes26 },
  { chapterId: 'summary-historia-america-espanhola', mechanism: 'Casta por origem e nascimento; cargo alto travado ao criollo', relation: 'Origem e local de nascimento fixam o degrau; o criollo tem riqueza mas não chega ao cargo alto, e o ressentimento alimenta a independência', status: 'em-validacao', evidencePaths: loteN('7b', 'summary-historia-america-espanhola', 3), notes: notes26 },
  { chapterId: 'summary-historia-reforma-religiosa', mechanism: 'Trento: dogma mantido e abusos corrigidos', relation: 'A venda de indulgências provoca a crítica de Lutero; Trento reafirma dogmas e corrige abusos, posição que não é nenhuma das duas anteriores', status: 'em-validacao', evidencePaths: loteN('7b', 'summary-historia-reforma-religiosa', 3), notes: notes26 },
  { chapterId: 'summary-historia-absolutismo', mechanism: 'Direito divino e contrato: dois caminhos, o mesmo trono', relation: 'Bossuet (base religiosa) e Hobbes (base racional e contratual, Leviatã, 1651) partem de fundamentos distintos e chegam ao mesmo poder absoluto', status: 'em-validacao', evidencePaths: loteN('7b', 'summary-historia-absolutismo', 3), notes: notes26 },
  { chapterId: 'summary-historia-iluminismo', mechanism: 'Uma lamparina da razão acende três propostas', relation: 'Da mesma base racionalista saem a separação dos poderes (Montesquieu), a soberania popular (Rousseau) e a liberdade de expressão (Voltaire)', status: 'em-validacao', evidencePaths: loteN('7b', 'summary-historia-iluminismo', 4), notes: notes26 },
  { chapterId: 'summary-historia-europa-no-seculo-xix', mechanism: 'Mesma classe operária, duas estratégias', relation: 'Do operariado saem o salto revolucionário de Marx e Engels (Manifesto, 1848) e a escada eleitoral da social-democracia (SPD)', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-europa-no-seculo-xix', 3), notes: notes26 },
  { chapterId: 'summary-historia-imperialismo-e-belle-epoque', mechanism: 'Cadeia de mando direta × indireta', relation: 'A França governa pelo funcionário europeu; o Reino Unido mantém a chefia local e reduz custo; ao lado, a partilha de Berlim (1884–1885)', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-imperialismo-e-belle-epoque', 3), notes: notes26 },
  { chapterId: 'summary-historia-primeira-guerra-mundial-1914-1918', mechanism: 'Alianças + pressão + faísca de Sarajevo', relation: 'A rede Tríplice Aliança × Tríplice Entente converte a crise balcânica em guerra continental; Sarajevo é estopim, não causa suficiente', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-primeira-guerra-mundial-1914-1918', 3), notes: notes26 },
  { chapterId: 'summary-historia-o-periodo-entreguerras-1918-1939', mechanism: 'Crise → totalitarismos → concessões → 1939', relation: 'A quebra de 1929 espalha a crise; surgem regimes totalitários; cada concessão (Renânia, Áustria, Tchecoslováquia) leva a 1939', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-o-periodo-entreguerras-1918-1939', 3), notes: notes26 },
  { chapterId: 'summary-historia-o-nazismo-na-alemanha', mechanism: 'Três rachaduras que só juntas derrubam', relation: 'Hiperinflação (1923), Depressão (1929) e democracia frágil: cada uma sozinha não basta; juntas abrem o caminho legal de 1933', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-o-nazismo-na-alemanha', 4), notes: notes26 },
  { chapterId: 'summary-historia-descolonizacao-afro-asiatica', mechanism: 'Duas trilhas até a independência', relation: 'Índia: passos não violentos até 1947, com partição; Argélia: guerra de 1954 a 1962, porque a França a via como território nacional', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-descolonizacao-afro-asiatica', 3), notes: notes26 },
  { chapterId: 'summary-historia-o-fim-da-guerra-fria', mechanism: 'Reformas soltam a pressão; dominós caem', relation: 'Perestroika e glasnost liberam tensões; sem intervenção soviética o Muro cai (1989), o Leste cai em cascata e a URSS vira 15 repúblicas (1991)', status: 'em-validacao', evidencePaths: loteN('8', 'summary-historia-o-fim-da-guerra-fria', 4), notes: notes26 },
  { chapterId: 'summary-geografia-clima-mundial', mechanism: 'Cinco fatores agem juntos sobre o mesmo ponto', relation: 'Latitude, altitude, continentalidade, correntes e relevo se combinam; nenhum explica sozinho o clima real de um lugar', status: 'em-validacao', evidencePaths: loteN('9', 'summary-geografia-clima-mundial', 4), notes: notes26 },
  { chapterId: 'summary-geografia-geomorfologia-mundial', mechanism: 'Idade e estabilidade tectônica classificam as estruturas', relation: 'Cráton antigo e erodido, bacia com camadas acumuladas e dobra jovem levantada por subducção na mesma crosta sul-americana', status: 'em-validacao', evidencePaths: loteN('9', 'summary-geografia-geomorfologia-mundial', 3), notes: notes26 },
  { chapterId: 'summary-geografia-biogeografia-mundial', mechanism: 'Latitude e circulação atmosférica ordenam os biomas', relation: 'O ar sobe e chove na ZCIT e desce seco perto de 30°; a temperatura cai do equador ao polo e os biomas seguem essa ordem', status: 'em-validacao', evidencePaths: loteN('9', 'summary-geografia-biogeografia-mundial', 3), notes: notes26 },
  { chapterId: 'summary-geografia-geopolitica-dos-recursos-hidricos', mechanism: 'Quem controla a cabeceira decide a água de quem vem depois', relation: 'Barragem sem acordo reduz a vazão; sem tratado há tensão; a dependência do Egito (>90%) torna a ameaça existencial', status: 'em-validacao', evidencePaths: loteN('9', 'summary-geografia-geopolitica-dos-recursos-hidricos', 4), notes: notes26 },
  { chapterId: 'summary-geografia-paisagem-espaco-geografico-e-ciencia-geografica', mechanism: 'A mesma paisagem, três explicações do espaço', relation: 'Determinismo: o meio decide; possibilismo: a sociedade escolhe; geografia crítica: poder e desigualdade organizam o espaço', status: 'em-validacao', evidencePaths: loteN('9', 'summary-geografia-paisagem-espaco-geografico-e-ciencia-geografica', 3), notes: notes26 },
  { chapterId: 'summary-geografia-producao-agricola-mundial', mechanism: 'Mecanização, escala e destino separam os sistemas', relation: 'O mesmo campo muda de máquina, tamanho e destino da colheita (casa, cooperativa, mercado mundial); os sistemas coexistem, não formam escada', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-producao-agricola-mundial', 3), notes: notes26 },
  { chapterId: 'summary-geografia-industria-i', mechanism: 'Quatro lógicas na mesma esteira de fábrica', relation: 'Taylor cronometra a tarefa; Ford a põe em linha contínua e paga para o operário comprar; Toyota corta estoque e dá várias máquinas a um operário', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-industria-i', 4), notes: notes26 },
  { chapterId: 'summary-geografia-o-espaco-industrial-brasileiro-i', mechanism: 'Café financia a fábrica; indústria atrai indústria', relation: 'O capital do café, a ferrovia e o porto fundam a indústria paulista; depois a aglomeração se retroalimenta via fornecedores e serviços', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-o-espaco-industrial-brasileiro-i', 2), notes: notes26 },
  { chapterId: 'summary-geografia-geografia-do-turismo', mechanism: 'Cada tipo de turismo ocupa o território de um jeito', relation: 'Sol e praia adensa a costa; cultural se apoia no patrimônio tombado; ecoturismo limita a entrada; negócios lota a metrópole nos dias úteis', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-geografia-do-turismo', 3), notes: notes26 },
  { chapterId: 'summary-geografia-blocos-economicos', mechanism: 'Cada grau soma um compromisso ao anterior', relation: 'Tarifas próprias viram tarifa externa comum; bens passam a circular com pessoas, capitais e serviços; moedas viram uma só', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-blocos-economicos', 4), notes: notes26 },
  { chapterId: 'summary-geografia-desigualdades-globais', mechanism: 'Periferia exporta mais para comprar o mesmo', relation: 'A deterioração dos termos de troca leva à substituição de importações atrás de tarifas altas, e daí a PIB industrial maior com baixa competitividade', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-desigualdades-globais', 3), notes: notes26 },
  { chapterId: 'summary-geografia-do-mundo-bipolar-ao-multipolar', mechanism: 'O polo soviético se desfaz e resta um', relation: 'O gasto militar sufoca a economia, as reformas soltam tensões, Muro e URSS caem (1989/1991), e os EUA ficam como única superpotência', status: 'em-validacao', evidencePaths: loteN('10', 'summary-geografia-do-mundo-bipolar-ao-multipolar', 4), notes: notes26 },
];
