import React from 'react';
import { type Scene } from './cenaKit';
import { Plate, Focus, Words, Note, Document, Figure, Palace, Factory, Coffee, Crowd, Ship, Strip } from './BrasilIllustration';

export function SegundoReinado({active}:Scene) {return <Plate title="Café, trabalho e Império" period="SEGUNDO REINADO · 1840–1889" active={active} description="Segundo Reinado: café do Vale do Paraíba ao oeste paulista, alternância de liberais e conservadores, fim do tráfico em 1850 e Guerra do Paraguai" caption="A produção cafeeira, a escravidão e sua crise coexistem com mudanças políticas e econômicas.">
 <Focus active={active} at={0}><Coffee x={113} y={235}/><Coffee x={180} y={255}/><Figure x={76} y={273} kind="worker" scale={.7}/><Words x={43} y={410} lines={['Vale do Paraíba → Oeste paulista','Expansão cafeeira e ferrovias']}/></Focus><path d="M211 328Q293 288 336 323M207 335Q295 295 340 331" className="brp-wood"/>
 <Figure x={389} y={197} kind="emperor"/><Palace x={391} y={307} scale={.55}/><Note x={226} y={135} to={[347,249]} lines={['parlamentarismo', '“às avessas”']}/><Document x={638} y={184} title="Lei Áurea · 1888" lines={['fim jurídico','da escravidão']}/><Ship x={624} y={350}/><Words x={538} y={455} lines={['Guerra do Paraguai · 1864–1870']}/><Note x={520} y={276} to={[513,324]} lines={['trabalho muda;', 'inclusão não é garantida']}/>
 <Strip active={active} items={[{title:"Café: Vale → oeste",lines:["Exportação cresce;", "ferrovias ligam", "áreas produtoras", "aos portos."]},{title:"Liberais / conservadores",lines:["Gabinetes da elite", "proprietária alternam;", "imperador controla", "a escolha ministerial."]},{title:"Fim do tráfico · 1850",lines:["Eusébio de Queirós;", "comércio interprovincial", "leva escravizados", "para o café."]},{title:"Guerra do Paraguai",lines:["Brasil, Argentina", "e Uruguai contra", "Paraguai; Exército", "ganha força política."]}]}/>
 </Plate>;}
export function RepublicaEspada({active}:Scene) {return <Plate title="A República nasce militar" period="DEODORO E FLORIANO · 1889–1894" active={active} description="República da Espada: Deodoro e Floriano no poder, Revolta da Armada no Rio e Revolução Federalista no Rio Grande do Sul, e Prudente de Morais eleito em 1894" caption="Primeiros governos republicanos: nova Constituição, crise econômica e conflitos políticos.">
 <Figure x={141} y={171} kind="soldier" scale={1.2}/><Words x={141} y={325} center lines={['Deodoro · 1889–1891']}/><Figure x={623} y={171} kind="soldier" scale={1.2}/><Words x={623} y={325} center lines={['Floriano · 1891–1894']}/><Document x={388} y={186} title="Constituição · 1891" lines={['federalismo','presidencialismo','Estado laico']}/><Palace x={384} y={367} scale={.5} closed/><Note x={39} y={127} to={[112,200]} lines={['golpe encerra', 'a monarquia']}/><Note x={529} y={387} to={[467,370]} lines={['oposição reprimida', 'pela força']}/><path d="M231 249H307M474 249H552" className="brp-link"/><Words x={35} y={410} lines={['Encilhamento: emissão,','especulação e inflação.']}/>
 <Strip active={active} items={[{title:"Deodoro · 1891",lines:["Dissolve o Congresso;", "a crise política leva", "à renúncia; Floriano", "assume a presidência."]},{title:"Revolta da Armada",lines:["Marinha ameaça", "bombardear o Rio;", "governo resiste com", "Exército e apoio civil."]},{title:"Federalista",lines:["No Rio Grande do Sul,", "federalistas enfrentam", "republicanos apoiados", "por Floriano."]},{title:"Prudente · 1894",lines:["Primeiro presidente", "civil da República;", "termina o governo", "militar direto."]}]}/>
 </Plate>;}
export function DemocraciaGuerraFria({active}:Scene) {return <Plate title="Democracia com fronteiras" period="REPÚBLICA LIBERAL · 1945–1964 · GUERRA FRIA" active={active} description="Democracia de 1946 sob a Guerra Fria: Constituição com eleições diretas e pluralismo, PCB cassado em 1947, crise de 1954 e posse de JK garantida em 1955" caption="Pluralismo partidário e mobilização social convivem com exclusões e pressão anticomunista.">
 <Palace x={389} y={263} scale={.82}/><Words x={389} y={381} center lines={['Congresso e Constituição de 1946']}/><Document x={115} y={181} title="Partidos" lines={['PSD · PTB · UDN','eleições competitivas']}/><Document x={644} y={181} title="PCB · 1947" lines={['registro cassado','anticomunismo']} stamp="EXCLUÍDO"/><Crowd x={146} y={372} banner="DIREITOS"/><Words x={542} y={351} lines={['Guerra Fria:','pressões internas','e alinhamento aos EUA.']}/><Note x={298} y={131} to={[389,205]} lines={['o voto se amplia,', 'mas há exclusões']}/><Note x={337} y={434} to={[246,419]} lines={['trabalhadores pressionam', 'por direitos e reformas']}/>
 <Strip active={active} items={[{title:"Constituição · 1946",lines:["Eleições e pluralismo;", "liberdade de imprensa;", "analfabetos ainda", "não podem votar."]},{title:"PCB cassado · 1947",lines:["Anticomunismo exclui", "partido votado em 1945;", "Dutra rompe com a URSS;", "pluralismo tem limites."]},{title:"Crise · 1954",lines:["Oposição civil, militar", "e pressão da imprensa;", "Vargas se suicida;", "carta-testamento."]},{title:"Posse de JK · 1955",lines:["Eleição contestada;", "contragolpe preventivo", "de Lott assegura a posse", "do presidente eleito."]}]}/>
 </Plate>;}
function Brasilia() {return <g transform="translate(385 291)"><path d="M-84 67H99M-73 65V-76h26V65M-35 65V-76h26V65M-73-63h26M-35-63h26" className="brp-stone"/><path d="M-151 64Q-110 14-68 64ZM15 25Q53 90 91 25ZM-160 72H111" className="brp-document"/><path d="M-73-49h26m-26 15h26m12-15h26m-26 15h26" className="brp-rule"/><path d="M-184 101Q-27 77 151 97" className="brp-water"/><text y="135" textAnchor="middle" className="brp-label">Brasília · inaugurada em 1960</text></g>;}
export function Desenvolvimentismo({active}:Scene) {return <Plate title="Industrializar e integrar o país" period="VARGAS, JK E JOÃO GOULART · 1950–1964" active={active} description="Desenvolvimentismo: Plano de Metas com 31 metas, Brasília inaugurada em 1960 no interior, Petrobras e montadoras estrangeiras, e a crise de 1961 a 1964" caption="Desenvolvimentismo combina ação estatal e capital privado; custos e disputas acompanham o crescimento.">
 <Brasilia/><Factory x={142} y={240} scale={.6}/><path d="M166 310Q213 337 236 361M177 315Q219 343 245 367" className="brp-wood"/><Words x={39} y={348} lines={['Indústria automobilística','e rodovias no Plano de Metas.']}/><path d="M562 304v-95h41v95ZM552 312h68M572 209l-4-34h21l-4 34M575 226v56" className="brp-stone"/><Words x={538} y={348} lines={['Petrobras · 1953','Estado e energia']}/><Document x={649} y={172} title="Plano de Metas" lines={['energia · transporte','indústria de base']}/><Note x={261} y={129} to={[366,219]} lines={['“50 anos em 5”', 'JK · 1956–1961']}/><Note x={39} y={414} to={[270,400]} lines={['crescimento traz', 'inflação e dívida']}/>
 <Strip active={active} items={[{title:"Plano de Metas",lines:["31 metas: infraestrutura", "e indústria de base;", "Estado e capital externo;", "“50 anos em 5”."]},{title:"Brasília · 1960",lines:["Nova capital no interior;", "símbolo de integração", "territorial e otimismo", "desenvolvimentista."]},{title:"Petrobras / montadoras",lines:["Petrobras estatal: 1953;", "JK atrai montadoras", "estrangeiras; tensão", "entre projetos econômicos."]},{title:"Crise · 1961–1964",lines:["Jânio renuncia em 1961;", "Goulart: parlamentarismo;", "plebiscito em 1963;", "golpe em abril de 1964."]}]}/>
 </Plate>;}
export function RegimeMilitarI({active}:Scene) {return <Plate title="Repressão e crescimento desigual" period="REGIME MILITAR · 1964–1973" active={active} description="Regime Militar I: na política, golpe de 1964, Atos Institucionais e AI-5 em 1968; na economia, milagre de 1968 a 1973 financiado por dívida externa" caption="Economia e repressão coexistem; crescimento do PIB não significa distribuição equivalente da renda.">
 <Palace x={168} y={244} scale={.58} closed/><Document x={144} y={379} title="AI-5 · 1968" lines={['cassações','suspensão de garantias']}/><Figure x={284} y={283} kind="soldier" scale={.85}/><Factory x={531} y={241} scale={.72}/><path d="M415 419V319M415 419H728M431 401Q511 393 552 357T702 332" className="brp-water"/><path d="M432 410H700" className="brp-danger"/><Words x={711} y={337} lines={['PIB']}/><Words x={600} y={445} lines={['salários comprimidos']}/><Note x={42} y={129} to={[119,216]} lines={['Congresso fechado;', 'censura e repressão']}/><Note x={415} y={135} to={[528,199]} lines={['“milagre” · 1968–1973', 'crédito e grandes obras']}/><path d="M365 133V448" className="brp-rule"/>
 <Strip active={active} items={[{title:'Golpe · 1964',lines:['Goulart deposto;','apoio civil e militar;','Atos Institucionais','e eleições indiretas.']},{title:'AI-5',lines:['Dezembro de 1968;','censura, tortura,','cassações e','desaparecimentos.']},{title:'“Milagre”',lines:['Infraestrutura e','crédito externo;','renda concentrada','e arrocho salarial.']},{title:'Dívida',lines:['Financiamento externo;','petróleo caro em 1973;','alta posterior de juros','agrava a dependência.']}]}/>
 </Plate>;}
export function RegimeMilitarII({active}:Scene) {return <Plate title="A abertura disputada nas ruas" period="TRANSIÇÃO · 1974–1988" active={active} description="Regime Militar II: abertura lenta, gradual e segura de 1974 a 1985, crise econômica, Diretas Já com a emenda rejeitada em 1984 e colégio eleitoral em 1985" caption="Diretas Já não conquistou eleição presidencial direta em 1984; a sucessão de 1985 foi indireta.">
 <Crowd x={225} y={297} banner="DIRETAS JÁ"/><Crowd x={169} y={366} banner="VOTO DIRETO"/><Figure x={66} y={289} kind="worker" scale={.9}/><Palace x={560} y={238} scale={.68}/><Document x={585} y={393} title="Constituição · 1988" lines={['direitos e cidadania','democracia']}/><path d="M344 327Q414 292 459 314" className="brp-link"/><path d="M400 312l18 22m0-22-18 22" className="brp-danger"/><Note x={36} y={135} to={[172,256]} lines={['praças cheias', 'em 1983–1984']}/><Note x={449} y={129} to={[555,202]} lines={['abertura controlada', 'pelos militares']}/><Words x={309} y={400} lines={['Emenda Dante','de Oliveira rejeitada','por margem estreita','em abril de 1984.']}/><Words x={40} y={434} lines={['Mobilização popular','pressiona a transição.']}/>
 <Strip active={active} items={[{title:'Abertura',lines:['Geisel: distensão;','AI-5 revogado, 1978;','anistia em 1979;','controle militar.']},{title:'Crise',lines:['Dívida e juros altos;','choque do petróleo;','inflação, recessão','e desemprego.']},{title:'Diretas Já',lines:['Movimento amplo','por eleição direta;','emenda não atinge','quórum necessário.']},{title:'1985 → 1988',lines:['Tancredo eleito','pelo colégio eleitoral;','Sarney assume;','nova Constituição.']}]}/>
 </Plate>;}
export const SCENES_LOTE14: Record<string, React.ComponentType<Scene>> = {
  'summary-historia-brasil-imperio-segundo-reinado-1840-1889': SegundoReinado,
  'summary-historia-a-republica-da-espada': RepublicaEspada,
  'summary-historia-republica-liberal-1945-1964-democracia-em-tempos-de-guerra-fria': DemocraciaGuerraFria,
  'summary-historia-republica-liberal-1945-1964-desenvolvimentismo-e-populismo': Desenvolvimentismo,
  'summary-historia-regime-militar-1964-1985-i': RegimeMilitarI,
  'summary-historia-regime-militar-1964-1985-ii': RegimeMilitarII,
};
export const HEADERS_LOTE14: Record<string, string> = {
  'summary-historia-brasil-imperio-segundo-reinado-1840-1889': 'economia, trabalho e guerra',
  'summary-historia-a-republica-da-espada': 'poder e crises do regime',
  'summary-historia-republica-liberal-1945-1964-democracia-em-tempos-de-guerra-fria': 'pluralismo e seus limites',
  'summary-historia-republica-liberal-1945-1964-desenvolvimentismo-e-populismo': 'projeto e tensões',
  'summary-historia-regime-militar-1964-1985-i': 'trilhas paralelas',
  'summary-historia-regime-militar-1964-1985-ii': 'transição controlada',
};
