import React from 'react';
import { type Scene } from './cenaKit';
import { Plate, Focus, Words, Note, Document, Figure, Palace, Factory, Radio, Ship, Strip } from './BrasilIllustration';

export function ProvisionalRoad({active}:Scene) {return <Plate title="Das armas à Constituição" period="VARGAS · GOVERNO PROVISÓRIO · 1930–1934" active={active} description="Governo Provisório de Vargas: da Revolução de 1930, pelo governo por decretos e pela revolta paulista de 1932, até a Constituição de 1934" caption="1930 rompe a ordem oligárquica; 1934 institucionaliza direitos e elege Vargas indiretamente.">
 <Focus active={active} at={0}><Figure x={100} y={158} kind="soldier"/><Figure x={156} y={167} kind="soldier"/><Words x={52} y={307} lines={['1930: deposição de','Washington Luís;','Júlio Prestes não assume.']}/></Focus>
 <Palace x={390} y={244} scale={.75}/><Figure x={390} y={188} scale={.72}/><Note x={253} y={123} to={[383,197]} lines={['poder concentrado', 'no Executivo']}/><Document x={643} y={226} title="1934" lines={['Constituição','Assembleia Constituinte']}/><path d="M211 220H249M515 220H561" className="brp-link"/><Words x={286} y={407} lines={['Interventores substituem','governadores estaduais.']}/><Words x={559} y={348} lines={['Direitos sociais; confirma','voto feminino e secreto','do Código de 1932.']}/><Note x={40} y={388} to={[207,437]} lines={['1932 · SP em armas', 'exige Constituição']}/>
 <Strip active={active} items={[{title:'Ruptura · 1930',lines:['Aliança Liberal e','movimento armado;','crise da sucessão','oligárquica.']},{title:'Provisório',lines:['Congresso fechado;','governo por decretos;','aliança com tenentes','e forças regionais.']},{title:'1932',lines:['Constitucionalistas','paulistas vencidos;','a demanda não era','separar São Paulo.']},{title:'1934',lines:['Vargas eleito pela','Constituinte;','eleição direta estava','prevista para 1938.']}]}/>
 </Plate>;}
export function CohenEscalation({active}:Scene) {return <Plate title="Da polarização ao golpe" period="GOVERNO CONSTITUCIONAL · 1934–1937" active={active} description="Governo constitucional de 1934 a 1937: AIB e ANL em disputa, Intentona de 1935, Plano Cohen forjado e golpe de 10 de novembro de 1937" caption="Plano Cohen era falso; a ameaça forjada foi usada como pretexto para o golpe de 1937.">
 <Palace x={385} y={264} scale={.75} closed/><Words x={385} y={386} center lines={['Congresso fechado · 10 de novembro de 1937']}/><Focus active={active} at={0}><Figure x={83} y={179} kind="soldier"/><Figure x={157} y={179} kind="worker"/><Words x={47} y={315} lines={['AIB: Plínio Salgado, 1932','ANL: frente antifascista']}/></Focus><Focus active={active} at={2}><Document x={637} y={219} title="Plano Cohen" lines={['ameaça inventada','por um integralista']} stamp="FALSO"/></Focus><Note x={243} y={131} to={[353,211]} lines={['emergência vira', 'concentração de poder']}/><path d="M205 237H249M548 230H569" className="brp-link"/><Words x={548} y={359} lines={['Constituição outorgada;','eleição de 1938 evitada.']}/><Note x={60} y={413} to={[236,411]} lines={['a repressão já', 'crescia desde 1935']}/>
 <Strip active={active} items={[{title:'Polarização',lines:['AIB de Plínio Salgado','e ANL de oposição;','mobilização política','e confrontos.']},{title:'Levantes · 1935',lines:['Natal, Recife e Rio;','fracassam; amplia-se','a repressão sob o','anticomunismo.']},{title:'Cohen · 1937',lines:['Documento forjado;','divulgado como plano','comunista para','justificar exceção.']},{title:'Estado Novo',lines:['Golpe com apoio','das Forças Armadas;','sem Constituinte;','partidos proibidos.']}]}/>
 </Plate>;}
export function WarMirror({active}:Scene) {return <Plate title="Ditadura dentro, Aliados fora" period="ESTADO NOVO · 1937–1945" active={active} description="Estado Novo: ditadura dentro do país e tropas brasileiras contra o fascismo na Itália; a contradição leva as Forças Armadas a depor Vargas em outubro de 1945" caption="A participação contra o Eixo expõe a contradição com a ditadura brasileira.">
 <Focus active={active} at={0}><Radio x={134} y={188}/><Words x={46} y={266} lines={['DIP (1939): censura e propaganda','controlam a informação.']}/><Palace x={149} y={366} scale={.48} closed/></Focus><path d="M284 126V441" className="brp-rule"/>
 <Factory x={428} y={278} scale={.65}/><Words x={329} y={367} lines={['CSN · criada em 1941','Volta Redonda; crédito','dos EUA aprovado em 1940']}/><Ship x={632} y={187}/><Words x={549} y={287} lines={['FEB na Itália · 1944–1945','Brasil entra na guerra','em 1942, com os Aliados.']}/><path d="M507 255Q544 218 549 197" className="brp-link"/><Note x={317} y={132} to={[430,215]} lines={['bases no Nordeste', 'e cooperação militar']}/><Note x={510} y={404} to={[398,427]} lines={['lutar contra o fascismo', 'e manter uma ditadura?']}/>
 <Strip active={active} items={[{title:"Contradição da guerra",lines:["Ditadura e DIP no Brasil;", "Aliados contra o Eixo;", "bases no Nordeste,", "FEB e cooperação industrial."]},{title:"Contradição insustentável",lines:["Vitória contra o fascismo", "reforça pressões por", "liberdade no Brasil;", "cresce a redemocratização."]},{title:"Queda de Vargas",lines:["Militares depõem Vargas", "em outubro de 1945;", "eleições; Vargas volta", "eleito em 1950."]}]}/>
 </Plate>;}
export function InequalityGate({active}:Scene) {return <Plate title="Renda, trabalho e proteção" period="BRASIL ATUAL · TRANSFORMAÇÕES DOS ANOS 2000" active={active} description="Brasil atual: Bolsa Família, valorização do salário mínimo e alta das commodities contribuem para a redução da desigualdade nos anos 2000" caption="Curva qualitativa, sem valores: múltiplos fatores contribuem para reduzir a desigualdade.">
 <Factory x={164} y={242} scale={.72}/><Figure x={246} y={255} kind="worker" scale={.8}/><Document x={448} y={215} title="Proteção social" lines={['transferência de renda','acesso a serviços']}/><Words x={57} y={369} lines={['Constituição Cidadã: direitos','Mais emprego formal','e renda do trabalho.']}/><Words x={363} y={324} lines={['Salário mínimo real','e políticas de renda.']}/>
 <g><path d="M589 168v158H737" className="brp-ink"/><path d="M600 187Q641 198 661 226T731 283" className="brp-water"/><Words x={597} y={144} lines={['Desigualdade']}/><Words x={594} y={352} lines={['Gini: queda nos','anos 2000']}/></g><Note x={55} y={131} to={[225,244]} lines={['trabalho importa']}/><Note x={351} y={411} to={[601,292]} lines={['contribuições', 'combinadas para', 'a queda da desigualdade']}/><path d="M281 303Q304 352 345 344M526 304H562" className="brp-link"/>
 <Strip active={active} items={[{title:"Bolsa Família",lines:["Programas de renda", "unificados em 2003;", "proteção social reduz", "a pobreza extrema."]},{title:"Salário mínimo",lines:["Valorização real", "atinge salários e", "benefícios vinculados", "ao piso nacional."]},{title:"Commodities",lines:["Exportações valorizadas", "favorecem crescimento,", "emprego e renda", "nos anos 2000."]},{title:"Fatores combinados",lines:["Políticas de renda", "e condições econômicas", "contribuem para a queda;", "não são requisitos únicos."]}]}/>
 </Plate>;}
export function NarratorBeam({active}:Scene) {return <Plate title="Quem conta a história de 1500?" period="HISTORIOGRAFIA · FONTES E PERSPECTIVAS" active={active} description="A História e o Brasil: o encontro de 1500 narrado do navio pela historiografia antiga e da aldeia pela recente, com as fontes escritas, arqueológicas e orais" caption="Paisagem imaginada: a mesma chegada pode ser narrada de perspectivas distintas.">
 <path d="M34 317Q193 278 366 314T744 313V426H34Z" className="brp-land"/><path d="M298 350Q498 313 747 347M306 374Q511 342 746 372M317 398Q565 365 746 398" className="brp-water"/><Ship x={562} y={211}/><path d="M64 294 127 231 190 294ZM75 290v61h104v-61M116 350v-33h22v33" className="brp-straw"/><path d="M181 301 241 243 296 301ZM195 299v55h87v-55" className="brp-wood-fill"/><path d="M90 223V147M90 151q-34-25-53 4m53-4q32-27 50 2" className="brp-leaf"/>
 <Document x={357} y={199} title="Carta de Caminha" lines={['registro português','não a única voz']}/><Words x={54} y={125} lines={['Povos indígenas:','territórios e histórias','anteriores à chegada.']}/><Note x={531} y={128} to={[579,198]} lines={['chegada para uns,', 'invasão para outros']}/><Note x={42} y={416} to={[185,343]} lines={['quem ficou fora', 'do documento escrito?']}/><Words x={508} y={435} lines={['Cruzar fontes muda a leitura.']}/>
 <Strip active={active} items={[{title:"Historiografia antiga",lines:["“Descobrimento” e", "“civilização”: leitura", "eurocêntrica minimiza", "a violência da conquista."]},{title:"Historiografia recente",lines:["Povos colonizados agem:", "resistem, negociam e", "transformam a sociedade;", "não são sujeitos passivos."]},{title:"Deslocamento",lines:["quem tem autoridade", "para narrar? Cruzar", "cartas e crônicas, fontes", "arqueológicas e orais."]}]}/>
 </Plate>;}
export const SCENES_LOTE6: Record<string, React.ComponentType<Scene>> = {
  'summary-historia-a-era-vargas': ProvisionalRoad,
  'summary-historia-a-era-vargas-o-governo-constitucional-1934-1937': CohenEscalation,
  'summary-historia-a-era-vargas-o-estado-novo': WarMirror,
  'summary-historia-o-brasil-atual': InequalityGate,
  'summary-historia-a-historia-e-o-brasil': NarratorBeam,
};
export const HEADERS_LOTE6: Record<string, string> = {
  'summary-historia-a-era-vargas': 'da revolução à Constituição',
  'summary-historia-a-era-vargas-o-governo-constitucional-1934-1937': 'escalada de pretextos',
  'summary-historia-a-era-vargas-o-estado-novo': 'contradição dentro e fora',
  'summary-historia-o-brasil-atual': 'condições combinadas',
  'summary-historia-a-historia-e-o-brasil': 'quem narra a história',
};
