import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowRight, BookOpen, Clock3, RotateCcw, Target } from 'lucide-react';
import type { DashboardGroup, SummaryProgressDashboardModel } from '../lib/summaryProgressDashboard';

type Group = 'disciplina' | 'banca' | 'fase';
const phaseLabels: Record<string, string> = { primeira: '1ª fase', segunda: '2ª fase', unica: 'Fase única' };

function Metric({ label, value, tone = 'text-zinc-900 dark:text-zinc-100' }: { label: string; value: number | string; tone?: string }) {
  return <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4"><p className={`text-2xl font-bold ${tone}`}>{value}</p><p className="text-xs text-zinc-500 mt-1">{label}</p></div>;
}

function GroupRows({ rows, group }: { rows: DashboardGroup[]; group: Group }) {
  if (!rows.length) return <p className="rounded-xl border border-dashed border-zinc-300 dark:border-zinc-700 p-6 text-sm text-zinc-500">Ainda não há tentativas com {group === 'fase' ? 'fase identificada' : `${group} identificada`}.</p>;
  return <div className="space-y-2">{rows.map((row) => <Link key={row.key} to={row.href} className="block rounded-xl border border-zinc-200 dark:border-zinc-800 p-4 hover:border-indigo-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"><div className="flex items-center justify-between gap-4"><span className="font-semibold">{group === 'fase' ? phaseLabels[row.key] ?? row.key : row.key}</span><span className="text-sm text-zinc-500">{row.accuracy}% · {row.attempted} {row.attempted === 1 ? 'questão' : 'questões'}</span></div><div className="mt-2 h-2 rounded-full bg-zinc-100 dark:bg-zinc-800" aria-label={`${row.accuracy}% de acerto`}><div className="h-2 rounded-full bg-indigo-500" style={{ width: `${row.accuracy ?? 0}%` }} /></div></Link>)}</div>;
}

export default function SummaryProgressDashboard({ model, loading = false, error = null, initialGroup = 'disciplina' }: { model: SummaryProgressDashboardModel; loading?: boolean; error?: string | null; initialGroup?: Group }) {
  const [group, setGroup] = useState<Group>(initialGroup);
  if (loading) return <div role="status" className="rounded-2xl border border-zinc-200 dark:border-zinc-800 p-8 text-center text-zinc-500"><BookOpen className="mx-auto mb-3 h-7 w-7 animate-pulse" />Carregando evolução dos resumos…</div>;
  const rows = group === 'disciplina' ? model.subjects : group === 'banca' ? model.boards : model.phases;

  return <section aria-labelledby="summary-progress-title" className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600">Medicina · prioridade Fuvest</p><h2 id="summary-progress-title" className="mt-1 text-2xl font-bold">Evolução dos resumos de Ana Júlia</h2><p className="mt-1 text-sm text-zinc-500">Evidências de leitura, recuperação ativa e revisão — cada indicador leva a uma ação.</p></div>{model.continueStudy && <Link to={model.continueStudy.href} className="inline-flex items-center justify-center rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Continuar {model.continueStudy.title}<ArrowRight className="ml-2 h-4 w-4" /></Link>}</div>
    {error && <div role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">{error}</div>}
    {model.brokenReferences > 0 && <div role="alert" className="flex items-start rounded-xl border border-zinc-300 bg-zinc-50 p-4 text-sm dark:border-zinc-700 dark:bg-zinc-900"><AlertTriangle className="mr-2 mt-0.5 h-4 w-4 shrink-0" />{model.brokenReferences} {model.brokenReferences === 1 ? 'referência histórica aponta' : 'referências históricas apontam'} para conteúdo removido. O histórico foi preservado sem link quebrado.</div>}
    {!model.hasStudyData ? <div className="rounded-2xl border border-dashed border-zinc-300 dark:border-zinc-700 p-8 text-center"><Target className="mx-auto h-8 w-8 text-indigo-500" /><h3 className="mt-3 font-bold">Comece por uma recuperação ativa</h3><p className="mx-auto mt-2 max-w-lg text-sm text-zinc-500">Abra um resumo e responda sem consultar. O painel só mostrará métricas depois de registrar evidências reais.</p><Link to="/resumos" className="mt-4 inline-flex items-center rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Ir para os resumos<ArrowRight className="ml-2 h-4 w-4" /></Link></div> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Acerto nas tentativas" value={`${model.overallAccuracy}%`} /><Metric label="Respostas corretas" value={model.answers.correct} tone="text-emerald-600" /><Metric label="Respostas parciais" value={model.answers.partial} tone="text-amber-600" /><Metric label="Respostas incorretas" value={model.answers.incorrect} tone="text-rose-600" /><Metric label="Questões pendentes" value={model.answers.pending} /></div>
      <div className="grid gap-4 sm:grid-cols-3"><Metric label="Revisões vencidas" value={model.reviews.overdue} tone="text-rose-600" /><Metric label="Revisões previstas" value={model.reviews.upcoming} /><Metric label="Revisões concluídas" value={model.reviews.completed} tone="text-emerald-600" /></div>
      <div className="flex flex-wrap gap-3"><Link to="/erros" className="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold hover:border-indigo-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-zinc-700">Abrir Caderno de Erros</Link><Link to="/revisoes" className="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold hover:border-indigo-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-zinc-700">Abrir Revisões Automáticas</Link></div>
      <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-4 flex items-center justify-between gap-3"><h3 className="font-bold">Desempenho acionável</h3><select aria-label="Agrupar evolução por" value={group} onChange={(event) => setGroup(event.target.value as Group)} className="rounded-lg border border-zinc-300 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"><option value="disciplina">Disciplina</option><option value="banca">Banca</option><option value="fase">Fase</option></select></div><GroupRows rows={rows} group={group} /></div>
        <div className="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="font-bold">Primeiros mecanismos a revisar</h3>{model.difficulties.length ? <ul className="mt-4 space-y-2">{model.difficulties.map((item) => <li key={item.label} className="flex justify-between rounded-lg bg-zinc-50 px-3 py-2 text-sm dark:bg-zinc-800"><span>{item.label}</span><span className="font-semibold">{item.count}×</span></li>)}</ul> : <p className="mt-4 text-sm text-zinc-500">Nenhum mecanismo ausente registrado.</p>}</div></div>
      {model.recurrences.length > 0 && <div className="rounded-2xl border border-rose-200 bg-rose-50/50 p-5 dark:border-rose-900 dark:bg-rose-950/20"><h3 className="flex items-center font-bold"><RotateCcw className="mr-2 h-5 w-5" />Erros reincidentes</h3><div className="mt-3 space-y-2">{model.recurrences.map((item) => item.href ? <Link key={`${item.summaryId}:${item.questionId}`} to={item.href} className="flex items-center justify-between rounded-lg bg-white px-3 py-3 text-sm dark:bg-zinc-900"><span>Retomar erro reincidente: {item.title}</span><span className="font-semibold">{item.attempts} tentativas</span></Link> : <p key={`${item.summaryId}:${item.questionId}`} className="rounded-lg bg-white px-3 py-3 text-sm dark:bg-zinc-900">{item.title} · referência removida</p>)}</div></div>}
      <div className="rounded-2xl border border-indigo-200 bg-indigo-50/50 p-5 dark:border-indigo-900 dark:bg-indigo-950/20"><h3 className="flex items-center font-bold"><Clock3 className="mr-2 h-5 w-5" />Prioridades Fuvest</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{model.priorities.map((item) => <Link key={item.id} to={item.href} className="rounded-lg bg-white p-3 text-sm dark:bg-zinc-900"><span className="font-semibold">{item.title}</span><span className="mt-1 block text-xs text-zinc-500">{item.subject} · {item.progress}% lido</span></Link>)}</div></div>
      {model.currentAffairs.length > 0 && <div className="rounded-2xl border border-emerald-200 bg-emerald-50/50 p-5 dark:border-emerald-900 dark:bg-emerald-950/20"><h3 className="font-bold">Atualidades essenciais</h3><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">Retome o contexto verificado e a leitura de prova pelo método A.T.U.A.L.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{model.currentAffairs.map((item) => <Link key={item.id} to={item.href} className="rounded-lg bg-white p-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 dark:bg-zinc-900"><span className="font-semibold">{item.title}</span><span className="mt-1 block text-xs text-zinc-500">{item.progress}% lido</span></Link>)}</div></div>}
    </>}
  </section>;
}
