import { chromium, type Page } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
const baseUrl=process.env.CRIVO_URL??'http://localhost:3012'; const output=path.resolve('docs/visual-personalizado/screenshots/matrizes-sistemas'); const errors:string[]=[];
const chapters=['summary-matematica-sistemas-de-equacoes','summary-matematica-tabelas-e-matrizes','summary-matematica-multiplicacao-de-matrizes','summary-matematica-determinantes','summary-matematica-discussao-de-sistemas-lineares'];
const noise=(x:string)=>/localhost:24678|\[vite\] failed to connect|WebSocket closed without opened/.test(x);
function monitor(page:Page,label:string){page.on('pageerror',e=>{if(!noise(e.message))errors.push(`${label}: ${e.message}`)});page.on('console',m=>{if(m.type()==='error'&&!noise(m.text()))errors.push(`${label}: ${m.text()}`)})}
async function open(page:Page,id:string){await page.goto(`${baseUrl}/visual?summary=${id}`,{waitUntil:'domcontentloaded'});const close=page.getByRole('button',{name:'Fechar',exact:true});if(await close.isVisible().catch(()=>false))await close.click();await page.getByTestId('visual-study-board').waitFor()}
async function overflow(page:Page,label:string){const [w,s]=await page.evaluate(()=>[document.documentElement.clientWidth,document.documentElement.scrollWidth]);if(s>w+1)errors.push(`${label}: overflow ${s} > ${w}`)}
await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({headless:true});try{for(const id of chapters){const p=await browser.newPage({viewport:{width:390,height:844}});monitor(p,id);await open(p,id);await overflow(p,id);await p.getByRole('slider').press('ArrowRight');await p.getByRole('tab',{name:'Testar'}).click();if(await p.getByTestId('visual-study-board').count())errors.push(`${id}: prancha visível em Testar`);await p.close()}const system=await browser.newPage({viewport:{width:1440,height:1000}});monitor(system,'sistema desktop');await open(system,chapters[0]);await system.screenshot({path:path.join(output,'sistema-desktop-claro.png'),fullPage:true});await system.close();const det=await browser.newPage({viewport:{width:375,height:812}});await det.addInitScript(()=>localStorage.setItem('crivo_theme','dark'));monitor(det,'determinante móvel');await open(det,chapters[3]);await det.screenshot({path:path.join(output,'determinante-mobile-escuro.png'),fullPage:true});await det.close();const discussion=await browser.newPage({viewport:{width:768,height:1024}});monitor(discussion,'discussão tablet');await open(discussion,chapters[4]);await discussion.getByRole('slider').fill('3');await discussion.screenshot({path:path.join(output,'discussao-tablet-claro.png'),fullPage:true});await discussion.close();const c=await browser.newContext({reducedMotion:'reduce',viewport:{width:768,height:1024}});const p=await c.newPage();monitor(p,'movimento reduzido');await open(p,chapters[2]);await c.close()}finally{await browser.close()}if(errors.length)throw new Error(errors.join('\n'));console.log(`QA concluído em ${output}`);
